const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const questions = [
// MATERNAL & CHILD
{s:'maternal',t:'Prenatal Care',q:'A primigravida at 20 weeks AOG asks how often she should feel fetal movement. The nurse correctly responds:',c:['At least 3 movements per hour','At least 10 movements in 2 hours','Once a day is normal','Fetal movement is not expected until 28 weeks'],ci:1,r:'Fetal kick counts: at least 10 movements within 2 hours is the accepted standard for reassuring fetal wellbeing.'},
{s:'maternal',t:'Labor & Delivery',q:'A patient in active labor has contractions every 2-3 minutes lasting 60 seconds. The FHR drops to 90 bpm during a contraction and returns to 140 bpm after. This is MOST likely:',c:['Early decelerations — reassuring','Late decelerations — non-reassuring','Variable decelerations','Accelerations'],ci:1,r:'Early decelerations mirror contractions and are caused by fetal head compression — a benign, reassuring finding.'},
{s:'maternal',t:'Labor & Delivery',q:'A nurse notes late decelerations on the fetal monitor. What is the PRIORITY intervention?',c:['Increase IV fluid rate','Reposition mother to left lateral position','Administer oxygen via face mask','Notify the physician'],ci:1,r:'Left lateral positioning is the FIRST action — it relieves aortocaval compression, improves placental perfusion, and may resolve late decelerations immediately.'},
{s:'maternal',t:'Postpartum',q:'A postpartum patient 2 hours after delivery has a uterus that is boggy and displaced to the right. What is the FIRST nursing action?',c:['Massage the fundus firmly','Have the patient void','Administer oxytocin as ordered','Notify the physician immediately'],ci:1,r:'A full bladder displaces the uterus and prevents it from contracting. Emptying the bladder is the first action before fundal massage.'},
{s:'maternal',t:'Postpartum',q:'The nurse assesses lochia rubra in a postpartum patient on day 5. This finding is:',c:['Normal — expected up to day 3-4','Abnormal — lochia should be serosa by day 4-5','Normal — can persist up to 2 weeks','Normal — depends on breastfeeding status'],ci:1,r:'Lochia rubra (red, bloody) normally lasts 1-3 days. By day 4-5, it should transition to lochia serosa (pink/brown). Persistent rubra may indicate subinvolution or infection.'},
{s:'maternal',t:'Newborn Care',q:'A newborn at 1 minute has HR 110, weak cry, some flexion, grimace, and blue hands/feet. The Apgar score is:',c:['6','7','8','9'],ci:1,r:'HR >100=2, weak cry=1, some flexion=1, grimace=1, blue extremities (acrocyanosis)=1. Total = 7. Acrocyanosis is normal in newborns.'},
{s:'maternal',t:'Newborn Care',q:'Which finding in a newborn requires IMMEDIATE nursing intervention?',c:['Acrocyanosis at 1 hour of life','Respiratory rate of 68 breaths/min','Molding of the skull','Presence of vernix caseosa'],ci:1,r:'Normal newborn RR is 30-60/min. A rate of 68 indicates tachypnea, which may signal respiratory distress syndrome or transient tachypnea requiring immediate assessment.'},
{s:'maternal',t:'Breastfeeding',q:'A breastfeeding mother reports sore nipples. Which assessment finding indicates INCORRECT latch?',c:['Baby\'s mouth covers most of the areola','Audible swallowing during feeding','Nipple pain throughout the entire feeding','Baby\'s lips are flanged outward'],ci:2,r:'Some nipple tenderness at latch-on is normal, but pain throughout the entire feeding indicates incorrect positioning or latch, requiring correction to prevent nipple trauma.'},
{s:'maternal',t:'Complications',q:'A patient at 34 weeks develops sudden severe headache, visual disturbances, and epigastric pain. BP is 160/110. The nurse suspects:',c:['Gestational hypertension','Mild preeclampsia','Severe preeclampsia / eclampsia risk','HELLP syndrome'],ci:2,r:'Severe preeclampsia criteria: BP ≥160/110 plus severe symptoms (headache, visual changes, epigastric pain). This requires immediate intervention to prevent seizures.'},
{s:'maternal',t:'Pediatric',q:'A 4-year-old is admitted with high fever and a petechial rash. The nurse\'s PRIORITY action is:',c:['Give antipyretics and monitor','Place on contact precautions and notify physician immediately','Obtain blood cultures and wait for results','Apply cool compress to the rash'],ci:1,r:'Petechial rash with fever in a child is a red flag for meningococcemia — a life-threatening emergency. Immediate isolation and physician notification are priorities.'},

// MEDSURG
{s:'medsurg',t:'Cardiac',q:'A patient with MI is experiencing chest pain radiating to the left arm. The nurse\'s FIRST action is:',c:['Administer aspirin 325mg','Obtain a 12-lead ECG','Administer sublingual nitroglycerin','Apply oxygen via nasal cannula'],ci:1,r:'A 12-lead ECG is the priority to confirm MI, identify the affected area, and guide treatment. Other interventions follow based on findings.'},
{s:'medsurg',t:'Cardiac',q:'A patient on digoxin reports nausea, vomiting, and seeing yellow-green halos. Pulse is 52 bpm. The nurse should:',c:['Administer the next dose as scheduled','Hold the digoxin and notify the physician','Give antiemetics and continue monitoring','Increase fluid intake'],ci:1,r:'These are classic signs of digoxin toxicity. The drug must be held immediately and the physician notified. Bradycardia and visual disturbances are serious toxic effects.'},
{s:'medsurg',t:'Respiratory',q:'A patient with asthma is using a peak flow meter. The reading is in the RED zone (below 50% personal best). The nurse should:',c:['Encourage continued activity','Administer rescue bronchodilator and seek emergency care','Increase fluid intake','Document and reassess in 1 hour'],ci:1,r:'Red zone (<50% personal best) indicates a medical emergency. Rescue bronchodilator should be administered immediately and emergency care sought.'},
{s:'medsurg',t:'Neurological',q:'A patient suddenly develops facial drooping, arm weakness, and slurred speech. The nurse\'s PRIORITY action is:',c:['Perform a full neurological assessment','Note the time of symptom onset immediately','Administer aspirin','Position in high Fowler\'s'],ci:1,r:'In suspected stroke, TIME IS CRITICAL. Noting exact time of symptom onset determines eligibility for tPA (within 3-4.5 hours). This is the absolute priority.'},
{s:'medsurg',t:'Neurological',q:'A patient with increased ICP is being positioned. Which position is MOST appropriate?',c:['Trendelenburg','Head of bed flat','Head of bed elevated 30 degrees, head midline','Right lateral position'],ci:2,r:'HOB 30 degrees with head midline promotes venous drainage from the brain, reducing ICP without compromising cerebral perfusion pressure.'},
{s:'medsurg',t:'Renal',q:'A patient with chronic kidney disease has a potassium level of 6.2 mEq/L. Which food should the nurse instruct the patient to AVOID?',c:['White rice','Bananas and oranges','White bread','Pasta'],ci:1,r:'Bananas and oranges are high in potassium. CKD patients must restrict potassium to prevent dangerous hyperkalemia (cardiac arrhythmias).'},
{s:'medsurg',t:'Endocrine',q:'A diabetic patient is found unresponsive with diaphoresis and cool clammy skin. Blood glucose is 42 mg/dL. The PRIORITY action is:',c:['Administer insulin per protocol','Give 50% dextrose IV or glucagon IM','Obtain IV access first','Call the rapid response team'],ci:1,r:'Severe hypoglycemia requires immediate glucose replacement. If IV access is available: D50W IV. If not: glucagon IM. Brain damage occurs within minutes without glucose.'},
{s:'medsurg',t:'Gastrointestinal',q:'A patient post-appendectomy reports sudden severe abdominal pain, rigid abdomen, and fever 39.5°C. The nurse suspects:',c:['Normal post-op pain','Wound infection','Peritonitis','Paralytic ileus'],ci:2,r:'Sudden severe pain, rigid abdomen (board-like), and fever following appendectomy indicate peritonitis — a surgical emergency from possible perforation or anastomotic leak.'},
{s:'medsurg',t:'Orthopedic',q:'A patient with a newly applied leg cast reports severe pain and tingling in the toes. Capillary refill is 4 seconds. The nurse should:',c:['Elevate the limb and reassess','Administer pain medication','Notify the physician immediately — suspect compartment syndrome','Apply ice over the cast'],ci:2,r:'Severe pain unrelieved by elevation, paresthesia, and delayed capillary refill (>2 sec) indicate compartment syndrome — a surgical emergency requiring fasciotomy.'},
{s:'medsurg',t:'Oncology',q:'A patient receiving chemotherapy develops a temperature of 38.5°C with an ANC of 450/mm³. The nurse recognizes this as:',c:['Expected side effect requiring routine monitoring','Febrile neutropenia — a medical emergency','Drug-induced fever — administer antipyretics only','Viral infection — isolate and observe'],ci:1,r:'Febrile neutropenia (ANC <500 + fever ≥38.3°C) is an oncologic emergency with high mortality risk. Immediate broad-spectrum antibiotics are required within 1 hour.'},

// PSYCHIATRIC
{s:'psychiatric',t:'Therapeutic Communication',q:'A depressed patient says "There\'s no point in living anymore." What is the BEST nursing response?',c:['"Don\'t say that, things will get better."','\"Are you having thoughts of harming yourself?\"','\"Why do you feel that way?\"','\"I\'ll get the doctor right away.\"'],ci:1,r:'Direct assessment of suicidal ideation is the therapeutic priority. Asking directly does not plant ideas — it opens communication and allows for safety planning.'},
{s:'psychiatric',t:'Therapeutic Communication',q:'A nurse says to an anxious patient: "Everything will be fine, don\'t worry." This is an example of:',c:['Empathy','Giving false reassurance','Active listening','Clarification'],ci:1,r:'Giving false reassurance dismisses the patient\'s feelings and blocks therapeutic communication. It invalidates their experience without addressing underlying concerns.'},
{s:'psychiatric',t:'Schizophrenia',q:'A patient with schizophrenia states "The CIA implanted a chip in my brain to monitor my thoughts." The nurse\'s BEST response is:',c:['"That must be very frightening for you."','\"The CIA doesn\'t do that — you\'re safe here.\"','\"Let me check your brain for chips.\"','\"Have you taken your medication today?\"'],ci:0,r:'Acknowledging the emotional content of a delusion without reinforcing or arguing against it is therapeutic. Arguing increases agitation; reinforcing worsens the delusion.'},
{s:'psychiatric',t:'Mood Disorders',q:'A patient with bipolar disorder in a manic episode is pacing, speaking rapidly, and has not slept in 2 days. The PRIORITY nursing intervention is:',c:['Engage the patient in group therapy','Provide a calm, low-stimulation environment and ensure safety','Encourage physical activity to use excess energy','Teach relaxation techniques'],ci:1,r:'Mania is characterized by hyperactivity and decreased need for sleep. Priority is safety and reducing stimulation. High-activity environments worsen mania.'},
{s:'psychiatric',t:'Anxiety',q:'A patient experiencing a panic attack is hyperventilating with tingling in the hands and feet. The FIRST nursing action is:',c:['Administer anxiolytic medication','Stay with the patient and speak in a calm, quiet voice','Leave the patient alone to calm down','Ask the patient to explain what triggered the attack'],ci:1,r:'Presence and calm reassurance are the first interventions. Leaving increases panic; interrogating about triggers during an attack is inappropriate timing.'},
{s:'psychiatric',t:'Substance Use',q:'A patient in alcohol withdrawal has tremors, diaphoresis, and a seizure. The nurse should FIRST:',c:['Restrain the patient','Protect the patient from injury and maintain airway','Administer thiamine IV','Obtain blood alcohol level'],ci:1,r:'Safety is the priority during a seizure. Protecting from injury and maintaining airway patency come before any medication or laboratory intervention.'},

// PHARMACOLOGY
{s:'pharmacology',t:'Drug Safety',q:'A patient is prescribed warfarin. Which laboratory value should the nurse monitor MOST closely?',c:['CBC with platelet count','PT/INR','aPTT','Serum creatinine'],ci:1,r:'Warfarin therapy is monitored using PT/INR. Therapeutic INR for most indications is 2.0-3.0. Values outside this range indicate over or under anticoagulation.'},
{s:'pharmacology',t:'Drug Safety',q:'A patient is receiving heparin infusion. The aPTT result is 3x the control value. The nurse should:',c:['Increase the heparin infusion rate','Continue at the current rate','Hold the heparin and notify the physician','Administer protamine sulfate immediately'],ci:2,r:'Therapeutic aPTT is 1.5-2.5x control. A value 3x control indicates supratherapeutic anticoagulation — heparin should be held and physician notified. Protamine is only given for significant bleeding.'},
{s:'pharmacology',t:'Antibiotics',q:'A patient is prescribed gentamicin. Which assessment is MOST important before and during therapy?',c:['Liver function tests','Blood glucose levels','Renal function and hearing assessment','Pulmonary function tests'],ci:2,r:'Aminoglycosides (gentamicin) are nephrotoxic and ototoxic. Renal function (BUN, creatinine) and hearing (audiometry) must be monitored throughout therapy.'},
{s:'pharmacology',t:'Cardiac Drugs',q:'A patient is prescribed metoprolol for hypertension. Which assessment finding should prompt the nurse to HOLD the medication?',c:['Blood pressure 150/90 mmHg','Heart rate 48 bpm','Respiratory rate 18/min','Blood glucose 110 mg/dL'],ci:1,r:'Beta-blockers like metoprolol should be held for HR <60 bpm. A rate of 48 indicates bradycardia — administering would further lower the heart rate dangerously.'},
{s:'pharmacology',t:'Analgesics',q:'A patient on morphine for cancer pain has a respiratory rate of 8/min and is difficult to arouse. The nurse should FIRST:',c:['Administer the next dose as scheduled','Hold morphine and administer naloxone as ordered','Position in high Fowler\'s and apply oxygen','Document findings and call physician'],ci:1,r:'RR <12 with decreased LOC indicates opioid-induced respiratory depression — an emergency. Naloxone (opioid antagonist) must be administered immediately while supporting ventilation.'},
];

async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
