const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
// PRENATAL CARE
{s:'np2',t:'Prenatal Care',q:'Using Naegele\'s rule, if the LMP is October 10, the EDD is:',c:['July 17','July 10','July 3','August 17'],ci:0,r:'Naegele\'s rule: subtract 3 months from LMP month, add 7 days to LMP day. October 10 → July 10 → July 17. EDD = July 17 of the following year.'},
{s:'np2',t:'Prenatal Care',q:'Which of the following is a PRESUMPTIVE sign of pregnancy?',c:['Positive pregnancy test','Hegar\'s sign','Amenorrhea and breast tenderness','Fetal heart tones heard by Doppler'],ci:2,r:'Presumptive signs are subjective signs felt by the woman — amenorrhea, breast tenderness, nausea/vomiting, urinary frequency, fatigue. They are least reliable. Probable signs include Hegar\'s sign and positive pregnancy test. Positive signs include fetal heart tones and ultrasound.'},
{s:'np2',t:'Prenatal Care',q:'A nurse is performing Leopold\'s maneuvers. The FIRST maneuver determines:',c:['Fetal lie','What is in the fundus — head or breech','Engagement of presenting part','Position of fetal back'],ci:1,r:'First Leopold\'s maneuver (fundal grip) — the examiner faces the patient\'s head and uses both hands to palpate the fundus to determine what fetal part occupies the fundus (head feels round, hard, and ballotable; breech feels soft and irregular).'},
{s:'np2',t:'Prenatal Care',q:'The normal fetal heart rate (FHR) range is:',c:['80-100 bpm','100-120 bpm','110-160 bpm','160-180 bpm'],ci:2,r:'Normal FHR is 110-160 beats per minute. Bradycardia is FHR below 110 bpm and tachycardia is above 160 bpm. Both require immediate assessment as they may indicate fetal distress or compromise.'},
{s:'np2',t:'Prenatal Care',q:'A pregnant woman at 20 weeks AOG should have a fundal height of approximately:',c:['At the symphysis pubis','At the umbilicus','Midway between umbilicus and xiphoid','At the xiphoid process'],ci:1,r:'Fundal height in cm approximately equals weeks of gestation (McDonald\'s rule). At 20 weeks, the fundus should be at or near the umbilicus. This rule is reliable from 18-34 weeks gestation.'},
{s:'np2',t:'Prenatal Care',q:'Which of the following is a DANGER SIGN during pregnancy requiring immediate referral?',c:['Mild ankle edema in the afternoon','Frequent urination in first trimester','Sudden severe headache with visual disturbances','Mild nausea in first trimester'],ci:2,r:'Sudden severe headache with visual disturbances may indicate severe preeclampsia or impending eclampsia — a life-threatening obstetric emergency. Other danger signs include vaginal bleeding, severe abdominal pain, decreased fetal movement, and high fever.'},
{s:'np2',t:'Prenatal Care',q:'Iron supplementation during pregnancy is recommended to prevent:',c:['Gestational diabetes','Iron deficiency anemia','Neural tube defects','Preeclampsia'],ci:1,r:'Iron supplementation (60mg elemental iron daily) is recommended throughout pregnancy to prevent iron deficiency anemia. Folic acid prevents neural tube defects and should be taken before conception and in the first trimester.'},
{s:'np2',t:'Prenatal Care',q:'A pregnant woman at 28 weeks has a blood pressure of 148/96 mmHg. The nurse recognizes this as:',c:['Normal blood pressure in pregnancy','Gestational hypertension','Chronic hypertension','Preeclampsia without severe features'],ci:1,r:'Gestational hypertension is BP ≥140/90 mmHg after 20 weeks gestation WITHOUT proteinuria. Preeclampsia requires both hypertension AND proteinuria (or other end-organ damage). This finding requires prompt medical evaluation and monitoring.'},
// LABOR AND DELIVERY
{s:'np2',t:'Labor and Delivery',q:'The FIRST stage of labor begins with the onset of regular contractions and ends with:',c:['Delivery of the placenta','Full cervical dilation of 10 cm','Crowning of the fetal head','Delivery of the baby'],ci:1,r:'The first stage of labor begins with onset of regular uterine contractions and ends with complete cervical dilation (10 cm). It has three phases: latent (0-3 cm), active (4-7 cm), and transition (8-10 cm).'},
{s:'np2',t:'Labor and Delivery',q:'During active labor, the nurse notes late decelerations on the fetal monitor. The PRIORITY intervention is:',c:['Increase IV fluid rate immediately','Reposition the mother to left lateral position','Administer oxygen via face mask','Notify the physician'],ci:1,r:'Left lateral positioning is the FIRST intervention for late decelerations — it relieves aortocaval compression, improves placental blood flow, and may resolve the decelerations. Then administer oxygen, increase IV fluids, and notify the physician if decelerations persist.'},
{s:'np2',t:'Labor and Delivery',q:'Early decelerations in fetal monitoring are caused by:',c:['Umbilical cord compression','Uteroplacental insufficiency','Fetal head compression during contractions','Fetal sleep cycles'],ci:2,r:'Early decelerations are mirror images of contractions (begin and end with contractions) caused by fetal head compression against the cervix or pelvis. They are benign, require no intervention, and are not associated with fetal distress.'},
{s:'np2',t:'Labor and Delivery',q:'A nurse observes a loop of umbilical cord protruding from the vagina. The PRIORITY nursing action is:',c:['Push the cord back into the vagina','Place patient in knee-chest or Trendelenburg position and call for help','Prepare for immediate vaginal delivery','Apply warm moist gauze only and wait'],ci:1,r:'Umbilical cord prolapse is an obstetric emergency. The priority is to relieve pressure on the cord — knee-chest or Trendelenburg position uses gravity to move the presenting part off the cord. Emergency cesarean section is usually required.'},
{s:'np2',t:'Labor and Delivery',q:'During the transition phase of labor, the nurse should expect the client to:',c:['Be calm and cooperative','Express desire to push and be irritable','Sleep between contractions','Request epidural anesthesia'],ci:1,r:'Transition (8-10 cm) is the most intense phase of labor. Contractions are 2-3 minutes apart, lasting 60-90 seconds. The woman typically feels an urge to push, may be irritable, and may feel out of control. Continuous supportive nursing care is essential.'},
{s:'np2',t:'Labor and Delivery',q:'The FOURTH stage of labor refers to:',c:['Full dilation to delivery of baby','Delivery of baby to delivery of placenta','First 1-2 hours after delivery of placenta','24 hours after delivery'],ci:2,r:'The fourth stage of labor is the first 1-2 hours after delivery of the placenta. This is the period of physiologic adjustment and is critical for monitoring for postpartum hemorrhage, monitoring uterine tone, vital signs, and bladder function.'},
{s:'np2',t:'Labor and Delivery',q:'A client in active labor has ROM (rupture of membranes). The FIRST nursing action is to:',c:['Ambulate the client to speed up labor','Assess the FHR immediately','Notify the physician','Time the contractions'],ci:1,r:'After ROM, the priority is to assess fetal heart rate immediately to detect cord prolapse or compression. The color, amount, and odor of amniotic fluid should also be assessed. Green-stained (meconium) fluid indicates possible fetal distress.'},
// POSTPARTUM
{s:'np2',t:'Postpartum Care',q:'During postpartum assessment, a boggy uterus displaced to the right suggests:',c:['Uterine atony','Bladder distension displacing the uterus','Retained placental fragments','Infection'],ci:1,r:'A full bladder is the most common cause of uterine displacement and boggy uterus in the early postpartum period. The nurse should assist the client to void first before massaging the fundus. If fundus remains boggy after voiding, administer oxytocin as ordered.'},
{s:'np2',t:'Postpartum Care',q:'Lochia rubra normally lasts for:',c:['1-3 days','3-7 days','7-14 days','2-6 weeks'],ci:0,r:'Lochia rubra (bright red, bloody) normally lasts 1-3 days postpartum. It transitions to lochia serosa (pinkish-brown) from days 3-10, then to lochia alba (yellowish-white) from days 10-21. Persistent rubra beyond day 3-4 may indicate subinvolution.'},
{s:'np2',t:'Postpartum Care',q:'A breastfeeding mother reports engorgement and pain 3 days postpartum. The nurse should advise:',c:['Stop breastfeeding temporarily','Apply warm compresses before feeding and feed frequently','Apply ice packs only','Use a breast pump exclusively'],ci:1,r:'For engorgement in a breastfeeding mother: apply warm compresses before feeding to stimulate letdown, feed frequently (8-12 times/24 hours), ensure proper latch, and gently massage breasts. Ice packs can be applied between feedings for comfort.'},
{s:'np2',t:'Postpartum Care',q:'Which of the following postpartum findings requires IMMEDIATE nursing intervention?',c:['Fundus firm at the umbilicus on day 1','Temperature of 38.5°C on day 3 postpartum','Mild perineal discomfort','Normal lochia serosa on day 5'],ci:1,r:'A temperature of 38.5°C (101.3°F) on postpartum day 3 suggests puerperal infection (endometritis is most common). Mild fever on day 1 may be due to dehydration; persistent or high fever requires immediate assessment and antibiotic therapy.'},
{s:'np2',t:'Postpartum Care',q:'Postpartum blues (baby blues) is characterized by:',c:['Severe depression requiring antidepressants','Mild, transient mood changes in the first 3-5 days after delivery','Inability to care for the baby for weeks','Hallucinations and confusion'],ci:1,r:'Postpartum blues affects 50-80% of new mothers — mild, transient mood fluctuations (crying, irritability, anxiety) occurring 3-5 days after delivery. It resolves spontaneously within 2 weeks. If symptoms persist beyond 2 weeks, assess for postpartum depression.'},
// NEWBORN CARE
{s:'np2',t:'Newborn Care',q:'A newborn\'s Apgar score at 1 minute shows: HR 110, weak cry, some flexion, grimace to stimulation, and pink body with blue extremities. The Apgar score is:',c:['5','6','7','8'],ci:2,r:'HR >100=2, weak cry=1, some flexion=1, grimace=1, acrocyanosis (pink body, blue extremities)=1. Total = 7. A score of 7-10 is normal. Acrocyanosis is normal in newborns due to peripheral vasoconstriction.'},
{s:'np2',t:'Newborn Care',q:'The nurse assesses a newborn\'s respiratory rate as 68 breaths per minute. This finding:',c:['Is within normal range for a newborn','Requires immediate nursing intervention','Is normal during active sleep','Indicates respiratory distress syndrome'],ci:1,r:'Normal newborn respiratory rate is 30-60 breaths per minute. A rate of 68 bpm is tachypnea, which may indicate respiratory distress syndrome, transient tachypnea of the newborn, or other respiratory problems requiring immediate assessment.'},
{s:'np2',t:'Newborn Care',q:'Per the Unang Yakap (EINC) protocol, the umbilical cord should be clamped:',c:['Immediately after birth','At 1-3 minutes after birth or when cord stops pulsating','Only after the placenta is delivered','After 5 minutes regardless of cord pulsation'],ci:1,r:'Delayed cord clamping (at 1-3 minutes or when cord stops pulsating) allows blood to transfuse from the placenta to the newborn, increasing iron stores and reducing risk of anemia. The Philippines mandates delayed cord clamping per EINC protocol.'},
{s:'np2',t:'Newborn Care',q:'Physiologic jaundice in newborns:',c:['Appears within 24 hours of birth','Appears after 24 hours and peaks at 3-5 days','Is always pathological','Requires phototherapy in all cases'],ci:1,r:'Physiologic jaundice appears AFTER 24 hours of life (typically day 2-3), peaks at 3-5 days, and resolves by 1-2 weeks in term infants. Jaundice appearing within 24 hours is ALWAYS pathological and requires immediate evaluation.'},
{s:'np2',t:'Newborn Care',q:'The newborn screening in the Philippines tests for which condition by collecting blood from the heel?',c:['Hearing defects','Congenital heart disease','Metabolic disorders such as congenital hypothyroidism and PKU','Visual defects'],ci:2,r:'Newborn screening collects blood from the heel (heel prick) on day 2-5 of life to screen for metabolic disorders including congenital hypothyroidism, phenylketonuria (PKU), congenital adrenal hyperplasia, glucose-6-phosphate dehydrogenase deficiency, and galactosemia.'},
{s:'np2',t:'Newborn Care',q:'The nurse is teaching a mother about normal newborn behavior. Which statement is INCORRECT?',c:['Newborns sleep 16-20 hours per day','Newborns can see clearly up to 20 feet away','Newborns prefer human faces and high-pitched voices','Milia (white spots on nose) are normal and will resolve spontaneously'],ci:1,r:'Newborns can see only 8-12 inches (20-30 cm) — the distance from breast to mother\'s face during feeding. Their visual acuity is approximately 20/400. The other statements are correct. Milia are blocked sebaceous glands that resolve without treatment.'},
// COMPLICATIONS OF PREGNANCY
{s:'np2',t:'Complications of Pregnancy',q:'A client at 32 weeks gestation experiences sudden painless bright red vaginal bleeding. The nurse suspects:',c:['Abruptio placentae','Placenta previa','Show of labor','Cervical erosion'],ci:1,r:'Placenta previa presents with painless, bright red vaginal bleeding in the third trimester, often without warning. The low-lying placenta bleeds as the lower uterine segment forms. Abruptio placentae typically presents with dark red, painful bleeding and uterine rigidity.'},
{s:'np2',t:'Complications of Pregnancy',q:'A client at 36 weeks develops severe headache, visual disturbances, epigastric pain, and BP 162/110. The nurse recognizes this as:',c:['Gestational hypertension','Mild preeclampsia','Severe preeclampsia','Chronic hypertension with superimposed preeclampsia'],ci:2,r:'Severe preeclampsia criteria: BP ≥160/110 AND at least one of: severe headache, visual disturbances, epigastric pain (right upper quadrant pain), pulmonary edema, or thrombocytopenia. Magnesium sulfate is given for seizure prophylaxis.'},
{s:'np2',t:'Complications of Pregnancy',q:'A client with severe preeclampsia is receiving magnesium sulfate. Which finding indicates toxicity?',c:['Urinary output of 35 ml/hour','Respiratory rate of 14 breaths/minute','Loss of patellar reflexes','Blood pressure of 140/90'],ci:2,r:'Magnesium sulfate toxicity signs include: loss of deep tendon reflexes (first sign), respiratory depression (<12 bpm), and cardiac arrest. Therapeutic level is 4-7 mEq/L. Calcium gluconate is the antidote and should be at bedside during MgSO4 infusion.'},
{s:'np2',t:'Complications of Pregnancy',q:'A client at 10 weeks gestation presents with severe nausea, vomiting, and vaginal bleeding. Ultrasound shows a "snowstorm pattern." The nurse suspects:',c:['Ectopic pregnancy','Threatened abortion','Hydatidiform mole','Placenta previa'],ci:2,r:'Hydatidiform mole presents with hyperemesis gravidarum (severe N&V), vaginal bleeding, a uterus larger than dates, and no fetal heart tones. Ultrasound shows a classic "snowstorm" pattern. Serum HCG is markedly elevated. Treatment is suction curettage followed by HCG monitoring.'},
{s:'np2',t:'Complications of Pregnancy',q:'A client at 8 weeks gestation presents with sudden severe unilateral lower abdominal pain and vaginal spotting. The nurse suspects:',c:['Threatened abortion','Ectopic pregnancy','Hydatidiform mole','Placenta previa'],ci:1,r:'Ectopic pregnancy classically presents with sudden, severe unilateral pain and vaginal bleeding in the first trimester. Risk factors include PID, previous ectopic, IUD use. It is a life-threatening emergency — rupture can cause severe hemorrhage and shock.'},
// PEDIATRIC NURSING
{s:'np2',t:'Pediatric Nursing',q:'According to Erikson\'s theory, the developmental task of a toddler (1-3 years) is:',c:['Trust vs. mistrust','Autonomy vs. shame and doubt','Initiative vs. guilt','Industry vs. inferiority'],ci:1,r:'Erikson\'s autonomy vs. shame and doubt (1-3 years) — toddlers develop a sense of independence and self-control. They assert autonomy through the word "no" and wanting to do things themselves. Supporting autonomy while maintaining safety is key in toddler care.'},
{s:'np2',t:'Pediatric Nursing',q:'A 6-month-old infant should be able to:',c:['Walk with support','Say 2-3 words','Sit with support and roll over','Draw circles'],ci:2,r:'At 6 months, expected milestones include: sitting with support, rolling front-to-back and back-to-front, reaching for and grasping objects, babbling, and recognizing caregivers. Walking with support is expected at 9-12 months.'},
{s:'np2',t:'Pediatric Nursing',q:'Which of the following is the MOST reliable indicator of dehydration in infants?',c:['Decreased urine output only','Sunken fontanelle and decreased skin turgor','Mild irritability','Dry lips'],ci:1,r:'Sunken anterior fontanelle combined with decreased skin turgor (skin tent remains when pinched) are the most reliable indicators of significant dehydration in infants. Poor skin turgor indicates loss of extracellular fluid volume.'},
{s:'np2',t:'Pediatric Nursing',q:'A 4-year-old child with high fever develops a generalized tonic-clonic seizure lasting 2 minutes that stops spontaneously. The PRIORITY nursing action is:',c:['Restrain the child to prevent injury','Insert a tongue blade to prevent biting','Position on side, protect from injury, and time the seizure','Administer antipyretics immediately'],ci:2,r:'During a febrile seizure: position child on side (prevents aspiration), protect from injury (pad surfaces, do not restrain), and time the seizure. NEVER insert objects in the mouth (can cause injury). Antipyretics are given AFTER the seizure ends.'},
{s:'np2',t:'Pediatric Nursing',q:'A mother asks when to start complementary feeding for her breastfed baby. The nurse correctly advises:',c:['At 3 months to prevent allergy','At 4 months when the baby can sit','At 6 months while continuing breastfeeding','At 1 year when breast milk is insufficient'],ci:2,r:'WHO and Philippine DOH recommend introducing complementary foods at 6 months while continuing breastfeeding up to 2 years. The baby should show readiness signs: sits with support, shows interest in food, and has good head control. Starting earlier increases infection and allergy risk.'},
{s:'np2',t:'Pediatric Nursing',q:'A child is prescribed amoxicillin for otitis media. The parent says symptoms resolved after 2 days and wants to stop the antibiotics. The nurse advises:',c:['Yes — stop when symptoms resolve to prevent resistance','Continue the full prescribed course even if symptoms resolve','Take half the dose for the remaining days','Switch to a natural remedy'],ci:1,r:'Completing the full antibiotic course is essential even after symptom resolution. Stopping early leads to incomplete eradication of bacteria, risk of recurrence, and development of antibiotic resistance. For otitis media, the full course is typically 10 days for children under 2 years.'},
{s:'np2',t:'Pediatric Nursing',q:'A child with acute rheumatic fever develops carditis. The nurse should prioritize:',c:['Encouraging active play and exercise','Enforcing strict bed rest to reduce cardiac workload','Administering antipyretics only','Monitoring blood glucose levels'],ci:1,r:'Acute rheumatic fever with carditis requires strict bed rest to reduce cardiac workload and prevent further damage to the heart valves. Activity restrictions continue until inflammatory markers normalize. Penicillin is given to eradicate group A streptococcus.'},
{s:'np2',t:'Pediatric Nursing',q:'Which of the following is the CORRECT position for a child with epiglottitis?',c:['Supine with neck hyperextended','Prone position','Sitting upright — tripod position','Left lateral position'],ci:2,r:'Children with epiglottitis instinctively assume the tripod position (sitting forward, neck extended, drooling) to maintain the airway. Never force the child to lie down as this can cause complete airway obstruction. The priority is securing the airway in a controlled setting.'},
// BREASTFEEDING
{s:'np2',t:'Breastfeeding',q:'A breastfeeding mother asks how she knows the baby is getting enough milk. The nurse should tell her:',c:['The baby sleeps for 4+ hours after each feeding','The baby has 6-8 wet diapers per day and gains weight','The breasts feel empty after feeding','The baby rarely cries'],ci:1,r:'Signs of adequate breastfeeding include: 6-8 wet diapers per day by day 4-5, regular stooling, audible swallowing during feeding, and steady weight gain after day 5 (birth weight regained by 10-14 days). These are objective indicators of milk transfer.'},
{s:'np2',t:'Breastfeeding',q:'A breastfeeding mother develops mastitis. The nurse should advise:',c:['Stop breastfeeding immediately to rest the breast','Continue breastfeeding or pumping, apply warm compresses, and seek antibiotics','Apply ice packs and stop feeding on the affected side','Use formula while on antibiotics'],ci:1,r:'Mastitis treatment includes: continuing to breastfeed or pump (empties breast and prevents abscess), warm compresses before feeding, antibiotics (typically dicloxacillin or cephalexin), rest, and analgesics. Stopping breastfeeding worsens mastitis by causing milk stasis.'},
{s:'np2',t:'Breastfeeding',q:'Which of the following indicates an INCORRECT latch during breastfeeding?',c:['Baby\'s mouth covers most of the areola','Audible swallowing during feeding','Nipple pain throughout the entire feeding session','Baby\'s lips are flanged outward (fish lip position)'],ci:2,r:'Pain throughout the entire feeding session (not just at latch-on) indicates incorrect positioning or latch. Signs of correct latch: mouth covers most of areola, lips flanged out, audible swallowing, no nipple pain after initial latch. Incorrect latch causes sore nipples and poor milk transfer.'},
// FAMILY PLANNING
{s:'np2',t:'Family Planning',q:'The Billings Ovulation Method (cervical mucus method) identifies peak fertility when cervical mucus is:',c:['Thick, white, and sticky','Absent — dry days are safe','Clear, thin, stretchy, and slippery (egg-white consistency)','Yellow-tinged and odorous'],ci:2,r:'Peak fertility coincides with ovulation when cervical mucus is clear, thin, stretchy (spinnbarkeit), and slippery — resembling raw egg whites. This mucus facilitates sperm transport. After ovulation, progesterone causes mucus to become thick and sticky.'},
{s:'np2',t:'Family Planning',q:'Which family planning method is CONTRAINDICATED in a woman with history of deep vein thrombosis (DVT)?',c:['Combined oral contraceptive pills','Progestin-only pills','Condoms','Natural family planning'],ci:0,r:'Combined oral contraceptive pills (containing estrogen) are absolutely contraindicated in women with history of DVT, PE, or stroke because estrogen increases coagulation factors and thrombotic risk. Progestin-only methods are safe alternatives for these patients.'},
{s:'np2',t:'Family Planning',q:'The Lactational Amenorrhea Method (LAM) is effective ONLY when:',c:['The baby is under 1 year old','The mother is exclusively breastfeeding, baby is under 6 months, and menstruation has not returned','The mother breastfeeds at least twice daily','The baby is under 3 months old'],ci:1,r:'LAM is 98% effective when ALL three criteria are met: exclusive breastfeeding (no supplements), infant is under 6 months of age, AND menstruation has not returned. If any criterion is not met, another contraceptive method must be used.'},
{s:'np2',t:'Family Planning',q:'A woman reports she took her last combined oral contraceptive pill 36 hours ago and had unprotected sex. She asks about emergency contraception. The nurse should advise:',c:['Emergency contraception is no longer needed if she missed only one pill','She should take 2 pills now and 2 pills in 12 hours and use backup contraception','She should restart a new pack immediately','Abstinence only for the rest of the cycle'],ci:1,r:'If a combined OCP is missed for more than 24-48 hours, take the missed pill as soon as remembered, continue with the pack, and use backup contraception for 7 days. For emergency contraception after unprotected sex, levonorgestrel (Plan B) should be taken within 72 hours.'},
];
async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} NP2 questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
