const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
// PSYCHIATRIC
{s:'psychiatric',t:'Therapeutic Communication',q:'A patient with depression refuses to eat. The nurse sits with the patient during mealtime without speaking. This technique is called:',c:['Active listening','Offering self / silent presence','Confrontation','Reflection'],ci:1,r:'Offering self means being physically present without demands — communicating acceptance and care through silent companionship, which is therapeutic for withdrawn patients.'},
{s:'psychiatric',t:'Therapeutic Communication',q:'A nurse responds to a patient by saying "You seem upset. Tell me more about what you are feeling." This is an example of:',c:['Giving advice','Reflection and open-ended questioning','False reassurance','Changing the subject'],ci:1,r:'Reflection acknowledges the patient\'s emotion and open-ended questioning encourages elaboration — both are therapeutic communication techniques.'},
{s:'psychiatric',t:'Therapeutic Communication',q:'Which response by the nurse is MOST therapeutic when a patient says "I feel like nobody cares about me"?',c:['"Of course people care about you!"','"That must be a very lonely feeling."','"Why do you think that?"','"You should focus on positive things."'],ci:1,r:'Empathic reflection validates the patient\'s feelings without judgment. Arguing, questioning "why," or redirecting are non-therapeutic responses.'},
{s:'psychiatric',t:'Schizophrenia',q:'A patient with schizophrenia is responding to internal stimuli, laughing inappropriately, and talking to someone unseen. The nurse should:',c:['Leave the patient alone until the episode passes','Calmly orient the patient and stay with them','Restrain the patient for safety','Ask the patient to describe what they are seeing'],ci:1,r:'Calm presence and gentle reality orientation are appropriate. Reinforcing hallucinations by asking for details or leaving without safety assessment are not therapeutic.'},
{s:'psychiatric',t:'Schizophrenia',q:'A patient on haloperidol develops sudden neck stiffness, eyes rolling upward, and muscle spasms. The nurse recognizes:',c:['Tardive dyskinesia','Acute dystonia','Neuroleptic malignant syndrome','Akathisia'],ci:1,r:'Acute dystonia — sudden sustained muscle contractions affecting neck (torticollis) and eyes (oculogyric crisis) — is an early EPS reaction to antipsychotics. Treat with anticholinergics (benztropine).'},
{s:'psychiatric',t:'Schizophrenia',q:'A patient on a typical antipsychotic develops repetitive lip smacking, tongue protrusion, and grimacing after 2 years of therapy. The nurse recognizes:',c:['Acute dystonia','Akathisia','Tardive dyskinesia','Pseudoparkinsonism'],ci:2,r:'Tardive dyskinesia is a late-onset EPS (after months/years) characterized by involuntary repetitive oral movements. It may be irreversible — early detection is critical.'},
{s:'psychiatric',t:'Mood Disorders',q:'A patient with major depressive disorder begins to show sudden improvement in mood and increased energy after weeks of depression. The nurse should:',c:['Document as positive progress and reduce monitoring','Increase suicide watch — sudden improvement may indicate decision to act on suicidal plan','Encourage the patient to discuss their improvement with family','Decrease antidepressant dose as patient is improving'],ci:1,r:'Sudden improvement in a depressed patient is a red flag — the patient may have decided to act on suicidal ideation and feels relief from having made that decision. Increased vigilance is required.'},
{s:'psychiatric',t:'Mood Disorders',q:'A patient with bipolar disorder is prescribed lithium. Which finding requires IMMEDIATE nursing action?',c:['Mild hand tremors','Polyuria and polydipsia','Coarse tremors, confusion, and vomiting','Mild nausea after taking the dose'],ci:2,r:'Coarse tremors, confusion, and vomiting indicate lithium toxicity (levels >1.5 mEq/L). This is an emergency — lithium must be withheld and physician notified immediately.'},
{s:'psychiatric',t:'Anxiety Disorders',q:'A patient with OCD spends 4 hours daily washing hands until they bleed. The nurse understands that compulsions are:',c:['Deliberate attempts to gain attention','Voluntary behaviors the patient enjoys','Anxiety-reducing rituals the patient feels compelled to perform','Signs of psychosis'],ci:2,r:'Compulsions are repetitive behaviors performed to reduce the anxiety caused by obsessive thoughts — not voluntary or pleasurable. Preventing them without treatment causes severe anxiety.'},
{s:'psychiatric',t:'Crisis Intervention',q:'A patient calls the crisis hotline and says "I have pills in my hand and I am ready to end it." The nurse\'s PRIORITY response is:',c:['Ask what type of pills they have','Keep the patient talking and send emergency services to their location','Tell the patient that suicide is not the answer','Ask about their reasons for wanting to die'],ci:1,r:'Active suicidal behavior with means present is an emergency. The priority is to keep the patient engaged while simultaneously dispatching emergency services — not to debate or extensively assess.'},
{s:'psychiatric',t:'Substance Use',q:'A nurse is caring for a patient withdrawing from heroin. Which set of symptoms should the nurse anticipate?',c:['Seizures and hallucinations','Muscle aches, yawning, rhinorrhea, and anxiety','Euphoria and hypersomnia','Bradycardia and respiratory depression'],ci:1,r:'Opioid withdrawal is characterized by flu-like symptoms: muscle aches, yawning, lacrimation, rhinorrhea, anxiety, and GI symptoms. Unlike alcohol withdrawal, seizures are NOT typical.'},
{s:'psychiatric',t:'Personality Disorders',q:'A patient with borderline personality disorder says to the nurse "You are the only one who understands me — the other nurses are terrible." The nurse recognizes this behavior as:',c:['Transference','Splitting','Projection','Manipulation'],ci:1,r:'Splitting is a defense mechanism in BPD where people are viewed as entirely good or bad. The nurse must maintain consistent boundaries and communicate with the team to prevent staff splitting.'},
{s:'psychiatric',t:'Child Psychiatry',q:'A mother reports her 8-year-old son has been inattentive in school, frequently loses things, cannot wait his turn, and runs around excessively. The nurse suspects:',c:['Autism spectrum disorder','Conduct disorder','ADHD','Oppositional defiant disorder'],ci:2,r:'ADHD presents with inattention, hyperactivity, and impulsivity across multiple settings. Symptoms must be present before age 12 and impair functioning in at least two settings.'},
// PHARMACOLOGY
{s:'pharmacology',t:'Antibiotics',q:'A patient is prescribed penicillin. Before administration, the nurse should FIRST:',c:['Check the patient\'s last meal time','Ask about allergy to penicillin or cephalosporins','Verify the physician\'s license','Check the patient\'s blood culture results'],ci:1,r:'Penicillin allergy is common and can cause anaphylaxis. Cross-reactivity with cephalosporins exists. Allergy history must always be verified before administration.'},
{s:'pharmacology',t:'Antibiotics',q:'A patient is on IV vancomycin. The nurse notices the patient\'s face, neck, and chest are red and flushed during infusion. This is MOST likely:',c:['Allergic reaction — stop infusion immediately','Red Man Syndrome — slow the infusion rate','Vancomycin toxicity — discontinue the drug','Normal expected reaction — continue as ordered'],ci:1,r:'Red Man Syndrome is caused by too-rapid vancomycin infusion causing histamine release — not a true allergy. Slowing the infusion rate (over 60+ minutes) resolves the reaction.'},
{s:'pharmacology',t:'Cardiac Drugs',q:'A patient with heart failure is prescribed furosemide. Which electrolyte imbalance should the nurse MOST closely monitor?',c:['Hypernatremia','Hyperkalemia','Hypokalemia','Hypercalcemia'],ci:2,r:'Furosemide is a loop diuretic that causes potassium loss (hypokalemia). This is dangerous in patients on digoxin — hypokalemia potentiates digoxin toxicity.'},
{s:'pharmacology',t:'Cardiac Drugs',q:'A patient is prescribed nitroglycerin for angina. Which instruction is MOST important?',c:['Take with food to prevent nausea','Store in a clear plastic container in the refrigerator','Take one tablet sublingually; may repeat every 5 minutes x3; if no relief, call emergency services','Take daily regardless of chest pain'],ci:2,r:'SL nitroglycerin: one tablet under the tongue, may repeat every 5 minutes for up to 3 doses. If pain persists after 3 doses/15 minutes, this may be MI — call emergency services.'},
{s:'pharmacology',t:'Anticoagulants',q:'A patient on warfarin has an INR of 5.8 and is actively bleeding. The nurse anticipates administering:',c:['Protamine sulfate','Vitamin K (phytonadione) and fresh frozen plasma','Naloxone','Flumazenil'],ci:1,r:'Warfarin reversal for serious bleeding: Vitamin K (reverses warfarin effect over hours) plus FFP (immediate clotting factors). Protamine reverses heparin, not warfarin.'},
{s:'pharmacology',t:'Neurological Drugs',q:'A patient with epilepsy is prescribed phenytoin. Which assessment is MOST important during long-term therapy?',c:['Blood glucose levels','Gum (gingival) condition and serum phenytoin levels','Liver enzymes only','Urine output and kidney function'],ci:1,r:'Phenytoin causes gingival hyperplasia (gum overgrowth) — requiring oral hygiene assessment. Serum levels (therapeutic: 10-20 mcg/mL) must be monitored to prevent toxicity.'},
{s:'pharmacology',t:'Diabetes Drugs',q:'A patient with type 2 diabetes is prescribed metformin. Which condition is a contraindication to this drug?',c:['Hypertension','Renal impairment (eGFR <30)','Hyperthyroidism','Mild obesity'],ci:1,r:'Metformin is contraindicated in renal impairment — it accumulates causing lactic acidosis, a rare but potentially fatal complication. eGFR must be checked before and during therapy.'},
{s:'pharmacology',t:'Corticosteroids',q:'A patient on long-term prednisone therapy. Which finding is an expected side effect the nurse should monitor?',c:['Hypoglycemia','Hyponatremia','Hyperglycemia and cushingoid features','Bradycardia'],ci:2,r:'Long-term corticosteroids cause hyperglycemia, weight gain, moon face, buffalo hump (Cushing\'s features), osteoporosis, and immunosuppression. Blood glucose monitoring is essential.'},
{s:'pharmacology',t:'Drug Interactions',q:'A patient is prescribed ciprofloxacin and also takes antacids. The nurse should instruct:',c:['Take both medications together with food','Take ciprofloxacin 2 hours before or 6 hours after antacids','Antacids enhance ciprofloxacin absorption — take together','Discontinue antacids while on ciprofloxacin'],ci:1,r:'Antacids (containing aluminum, magnesium, or calcium) chelate ciprofloxacin and significantly reduce its absorption. Separate administration by at least 2 hours before or 6 hours after.'},
{s:'pharmacology',t:'Pain Medications',q:'A nurse is about to administer meperidine (Demerol) to an elderly patient. Which concern is MOST important?',c:['High risk for constipation','Normeperidine accumulation causing seizures in elderly','Risk of respiratory depression identical to other opioids','Potential for nausea and vomiting'],ci:1,r:'Meperidine metabolizes to normeperidine — a CNS stimulant that accumulates especially in elderly and renal patients, causing tremors and seizures. Meperidine is generally avoided in elderly patients.'},
{s:'pharmacology',t:'Psychiatric Drugs',q:'A patient on an MAOI antidepressant asks what foods to avoid. The nurse correctly instructs to avoid:',c:['Dairy products and eggs','Aged cheeses, cured meats, and red wine','Fresh fruits and vegetables','White bread and pasta'],ci:1,r:'MAOIs inhibit monoamine oxidase — tyramine-rich foods (aged cheese, cured meats, red wine) cannot be metabolized, causing potentially fatal hypertensive crisis (tyramine reaction).'},
];

async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
