const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
// COMMUNITY HEALTH
{s:'community',t:'Epidemiology',q:'A disease has a case fatality rate of 80%. This means:',c:['80% of the population will get the disease','80% of those who get the disease will die','80% of deaths are caused by this disease','The disease affects 80 per 100,000 population'],ci:1,r:'Case fatality rate = (deaths from disease / cases of disease) x 100. It measures the severity/lethality of a disease among those who are infected.'},
{s:'community',t:'Epidemiology',q:'A nurse notes that dengue cases increase every rainy season in a barangay. This pattern is called:',c:['Epidemic','Endemic','Pandemic','Sporadic'],ci:1,r:'Endemic means a disease is consistently present in a particular geographic area or population. Seasonal increases in dengue in the same area every year is endemic behavior.'},
{s:'community',t:'Epidemiology',q:'During a foodborne illness outbreak, 40 out of 200 people who ate at a fiesta developed diarrhea. What is the attack rate?',c:['10%','20%','40%','80%'],ci:1,r:'Attack rate = (ill persons / persons exposed) x 100 = (40/200) x 100 = 20%.'},
{s:'community',t:'Family Nursing',q:'A family with a member who has tuberculosis continues to live in a crowded one-room house despite health teachings. Using the family nursing typology, this is classified as:',c:['Health deficit','Health threat','Foreseeable crisis','Health problem already occurring'],ci:1,r:'A health threat is a condition that may lead to disease or failure to maintain health. Overcrowded living with a TB member poses a risk but no disease has yet occurred in others.'},
{s:'community',t:'Family Nursing',q:'The community health nurse prioritizes a family with an active TB case, a malnourished child, and an uncontrolled diabetic. Which problem should be addressed FIRST?',c:['Malnutrition in the child','Uncontrolled diabetes','Active tuberculosis','All problems equally'],ci:2,r:'Active TB is an infectious disease threatening not just the family but the community. Communicable diseases with public health implications take priority in community nursing.'},
{s:'community',t:'Home Visit',q:'During a home visit, the nurse observes a mother giving undiluted cow\'s milk to her 3-month-old infant. The nurse\'s BEST action is:',c:['Report the mother to social services','Educate the mother about appropriate infant feeding','Document the observation only','Ask the father to intervene'],ci:1,r:'Health education is the primary tool of community health nursing. Cow\'s milk is inappropriate for infants under 12 months — the nurse should educate without judgment.'},
{s:'community',t:'Levels of Prevention',q:'A stroke patient undergoes physical therapy to regain lost function. This represents:',c:['Primary prevention','Secondary prevention','Tertiary prevention','Health promotion'],ci:2,r:'Tertiary prevention aims to reduce disability and restore function after disease has occurred — rehabilitation is the hallmark of tertiary prevention.'},
{s:'community',t:'Levels of Prevention',q:'A nurse administers tetanus toxoid to a pregnant woman. This is an example of:',c:['Primary prevention','Secondary prevention','Tertiary prevention','Passive immunization'],ci:0,r:'Immunization prevents disease before it occurs — this is primary prevention. Tetanus toxoid stimulates active immunity in the mother, providing protection for both mother and newborn.'},
{s:'community',t:'Immunization',q:'BCG vaccine is given at birth. What disease does it primarily protect against?',c:['Hepatitis B','Severe forms of tuberculosis (TB meningitis, miliary TB)','Pertussis','Measles'],ci:1,r:'BCG (Bacillus Calmette-Guérin) primarily protects against severe disseminated forms of TB in children — TB meningitis and miliary TB — rather than pulmonary TB in adults.'},
{s:'community',t:'Immunization',q:'A child received the measles vaccine at 9 months. When should the second dose be given per Philippine EPI?',c:['12 months','15 months','18 months','24 months'],ci:1,r:'Per Philippine EPI, the first MMR/measles dose is at 9 months and the second dose (MR vaccine) is given at 15 months for complete protection.'},
{s:'community',t:'Nutrition',q:'A 2-year-old child has a weight-for-height z-score of -3 SD. This is classified as:',c:['Normal','Mild wasting','Moderate wasting','Severe acute malnutrition (SAM)'],ci:3,r:'Weight-for-height z-score below -3 SD indicates severe acute malnutrition (SAM) — requires urgent therapeutic feeding intervention per WHO guidelines.'},
{s:'community',t:'Nutrition',q:'A nurse is conducting a nutritional assessment. Which anthropometric measurement BEST reflects long-term nutritional status in children?',c:['Weight-for-age','Height-for-age (stunting)','Weight-for-height (wasting)','Mid-upper arm circumference'],ci:1,r:'Height-for-age reflects cumulative long-term nutritional status. Stunting (low height-for-age) indicates chronic malnutrition occurring over months to years.'},
{s:'community',t:'Tuberculosis',q:'A patient on anti-TB therapy develops yellow discoloration of skin and sclera. Which drug is MOST likely responsible?',c:['Ethambutol','Rifampicin','Isoniazid','Pyrazinamide'],ci:3,r:'Pyrazinamide is the most hepatotoxic first-line anti-TB drug. Jaundice (yellow skin/sclera) signals hepatotoxicity — the drug must be held and liver function evaluated.'},
{s:'community',t:'Tuberculosis',q:'A patient completes 6 months of anti-TB treatment and three consecutive sputum smears are negative. This is classified as:',c:['Treatment completed','Cured','Treatment success','Defaulted'],ci:1,r:'"Cured" specifically means smear-positive TB patient who completed treatment AND has negative sputum smears at end of treatment. "Treatment completed" applies to smear-negative cases.'},
{s:'community',t:'Environmental Health',q:'The nurse teaches a family about safe water. Which method MOST effectively kills pathogens in drinking water?',c:['Filtering through cloth','Storing in a clay pot','Boiling for at least 1 minute','Adding a pinch of salt'],ci:2,r:'Boiling water for at least 1 minute (3 minutes at high altitude) kills all pathogenic microorganisms including bacteria, viruses, and parasites.'},
{s:'community',t:'Maternal & Child',q:'A community health nurse is conducting a prenatal visit. Which finding requires IMMEDIATE referral?',c:['Fundal height equal to weeks of gestation','Fetal heart rate of 144 bpm','Absent fetal movement for 12 hours','Mild ankle edema in the afternoon'],ci:2,r:'Absent fetal movement for 12 hours is a danger sign requiring immediate evaluation for fetal distress or demise. Normal kick count is at least 10 movements in 2 hours.'},
{s:'community',t:'School Health',q:'A school nurse finds a student with a temperature of 38.8°C, headache, and a fine rash on the trunk. The nurse should:',c:['Give antipyretics and send back to class','Isolate the student and notify parents for pickup','Apply calamine lotion and monitor','Give the student water and rest in the clinic'],ci:1,r:'Fever with rash may indicate a communicable disease (measles, chickenpox, rubella). The student must be isolated immediately and excluded from school until cleared.'},
{s:'community',t:'Occupational Health',q:'A factory nurse conducts annual chest X-rays for workers exposed to silica dust. This is an example of:',c:['Primary prevention','Health promotion','Secondary prevention','Tertiary prevention'],ci:2,r:'Annual screening for workers at risk of occupational disease is secondary prevention — early detection before symptoms appear.'},

// MATERNAL & CHILD
{s:'maternal',t:'Prenatal Care',q:'A nurse is calculating the expected date of delivery (EDD) using Naegele\'s rule. LMP is July 10. The EDD is:',c:['April 17','April 10','April 3','May 17'],ci:0,r:'Naegele\'s rule: subtract 3 months from LMP, add 7 days, add 1 year. July 10 → April 10 → April 17. EDD = April 17 of the following year.'},
{s:'maternal',t:'Prenatal Care',q:'A pregnant woman at 32 weeks has a fundal height of 28 cm. The nurse should:',c:['Document as normal variation','Reassure — fundal height is always approximate','Report to physician — may indicate IUGR or oligohydramnios','Increase caloric intake immediately'],ci:2,r:'Fundal height in cm should approximately equal weeks of gestation (±2 cm). At 32 weeks, expected is 30-34 cm. A measurement 4 cm below suggests IUGR or oligohydramnios — physician referral is needed.'},
{s:'maternal',t:'Prenatal Care',q:'Which danger sign during pregnancy requires IMMEDIATE medical attention?',c:['Mild nausea in the first trimester','Increased vaginal discharge without odor','Sudden gush of fluid from the vagina at 28 weeks','Mild lower back pain after walking'],ci:2,r:'Sudden gush of fluid at 28 weeks suggests premature rupture of membranes (PROM) — a risk for cord prolapse, infection, and preterm labor requiring immediate evaluation.'},
{s:'maternal',t:'Labor & Delivery',q:'A patient is in transition phase of labor. Which assessment finding is EXPECTED?',c:['Contractions every 10 minutes lasting 30 seconds','Cervical dilation of 4-7 cm','Intense contractions every 2-3 minutes, irritability, urge to push','Rupture of membranes only'],ci:2,r:'Transition (8-10 cm dilation) is the most intense phase — contractions are 2-3 min apart, lasting 60-90 seconds, with the patient feeling an urge to push and often feeling overwhelmed.'},
{s:'maternal',t:'Labor & Delivery',q:'A nurse observes a loop of umbilical cord protruding from the vagina. The PRIORITY nursing action is:',c:['Push the cord back in','Place the patient in knee-chest or Trendelenburg position and call for help','Prepare for immediate vaginal delivery','Apply warm moist gauze to the cord and wait'],ci:1,r:'Cord prolapse is an obstetric emergency. The priority is to relieve pressure on the cord by positioning (knee-chest or Trendelenburg) to prevent fetal hypoxia while preparing for emergency cesarean.'},
{s:'maternal',t:'Postpartum',q:'A postpartum patient on day 3 reports painful, hard, engorged breasts. She is not breastfeeding. The nurse should advise:',c:['Apply warm compresses and express milk regularly','Wear a supportive bra, apply ice packs, and avoid stimulation','Take prescribed bromocriptine to stop milk production','Massage the breasts firmly every 2 hours'],ci:1,r:'For non-breastfeeding mothers, engorgement is managed with ice packs (reduce blood flow), supportive bra, and avoiding nipple stimulation. Warm compresses and expression encourage milk production.'},
{s:'maternal',t:'Newborn Care',q:'A newborn is placed skin-to-skin with the mother immediately after birth. Which statement BEST explains the rationale?',c:['It prevents neonatal hypoglycemia only','It promotes thermoregulation, bonding, and initiation of breastfeeding','It replaces the need for vitamin K administration','It prevents jaundice in the newborn'],ci:1,r:'Skin-to-skin (kangaroo care) immediately after birth promotes thermoregulation (prevents hypothermia), stimulates early breastfeeding, and promotes maternal-infant bonding.'},
{s:'maternal',t:'Newborn Care',q:'A newborn develops jaundice on day 1 of life. The nurse recognizes this as:',c:['Physiologic jaundice — normal finding','Pathologic jaundice — requires immediate evaluation','Breastfeeding jaundice — advise formula supplementation','Expected finding in all newborns — no action needed'],ci:1,r:'Jaundice within the first 24 hours of life is ALWAYS pathologic — most commonly due to Rh or ABO incompatibility. Physiologic jaundice appears after 24 hours (day 2-3).'},
{s:'maternal',t:'Complications',q:'A patient at 38 weeks experiences painless, bright red vaginal bleeding. The nurse suspects:',c:['Placental abruption','Placenta previa','Bloody show of labor','Cervical laceration'],ci:1,r:'Placenta previa presents with painless bright red vaginal bleeding in the third trimester — the placenta covers the cervical os, causing bleeding as the cervix begins to efface.'},
{s:'maternal',t:'Pediatric',q:'A nurse is assessing a 6-month-old infant. Which developmental milestone is EXPECTED at this age?',c:['Walking with support','Saying 2-3 word sentences','Sitting with support and rolling over','Drawing circles'],ci:2,r:'At 6 months, expected milestones include sitting with support, rolling front-to-back and back-to-front, reaching for objects, and babbling. Walking with support is expected at 9-12 months.'},
{s:'maternal',t:'Pediatric',q:'A child with a high fever develops a generalized tonic-clonic seizure lasting 2 minutes and stops spontaneously. The nurse\'s PRIORITY action is:',c:['Restrain the child to prevent injury','Insert a tongue blade to prevent biting','Position on the side, protect from injury, and time the seizure','Administer antipyretics immediately'],ci:2,r:'During a seizure: lateral position prevents aspiration, protect from injury, and time the seizure. Never restrain or insert objects in the mouth. Antipyretics are given AFTER the seizure resolves.'},
];

async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
