const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
{s:'np1',t:'Epidemiology',q:'The number of NEW cases of a disease in a population during a specific time period is called:',c:['Prevalence rate','Incidence rate','Morbidity rate','Mortality rate'],ci:1,r:'Incidence rate measures NEW cases occurring in a defined population during a specified time period. Prevalence includes all existing cases (new and old) at a given point in time.'},
{s:'np1',t:'Epidemiology',q:'During an outbreak, 25 out of 100 susceptible children developed measles. The attack rate is:',c:['10%','15%','25%','50%'],ci:2,r:'Attack rate = (number of cases / number susceptible) x 100 = (25/100) x 100 = 25%. Attack rate is used during outbreaks to measure the proportion of exposed persons who develop the disease.'},
{s:'np1',t:'Epidemiology',q:'Which of the following BEST describes an endemic disease?',c:['A disease that occurs worldwide','A disease that is constantly present in a specific geographic area','A sudden increase in disease cases above the expected level','A disease that spreads across multiple continents'],ci:1,r:'Endemic means a disease is habitually present in a particular geographic area at a consistent expected level. Dengue fever is endemic in the Philippines. An epidemic is a sudden increase above the expected level.'},
{s:'np1',t:'Epidemiology',q:'The leading cause of morbidity in the Philippines is:',c:['Tuberculosis','Acute respiratory infections','Hypertension','Diabetes mellitus'],ci:1,r:'Acute respiratory infections consistently rank as the top cause of morbidity in the Philippines, especially in children under 5 years. They are the leading reason for outpatient consultations.'},
{s:'np1',t:'Epidemiology',q:'Contaminated water causing cholera is an example of which mode of disease transmission?',c:['Contact transmission','Vehicle transmission','Airborne transmission','Vector-borne transmission'],ci:1,r:'Vehicle transmission occurs through contaminated inanimate intermediaries such as food, water, blood products, or fomites. Contaminated water is a classic vehicle of cholera transmission.'},
{s:'np1',t:'Epidemiology',q:'The case fatality rate (CFR) measures:',c:['The proportion of the population that dies from a disease','The proportion of diagnosed cases that die from the disease','The number of deaths per 1,000 population','The risk of dying from any cause'],ci:1,r:'CFR = (deaths from disease / confirmed cases) x 100. It measures the severity/lethality of a disease among those infected. A high CFR indicates a highly lethal disease.'},
{s:'np1',t:'Epidemiology',q:'Dengue fever is a notifiable disease in the Philippines that must be reported within:',c:['1 week','72 hours','24 hours','1 month'],ci:2,r:'Dengue fever requires immediate reporting (within 24 hours) to health authorities. Timely reporting enables prompt public health response to prevent epidemics.'},
{s:'np1',t:'Epidemiology',q:'Which of the following describes a PANDEMIC?',c:['A disease present at a constant level in a community','An unusual increase of disease in a community','A disease affecting people in multiple countries worldwide','A disease limited to a single province'],ci:2,r:'A pandemic is an epidemic that has spread across multiple countries or continents, affecting a large number of people. COVID-19 and Influenza A H1N1 are examples of pandemics.'},
{s:'np1',t:'Levels of Prevention',q:'A community health nurse provides iron supplementation to pregnant women to prevent anemia. This is an example of:',c:['Primordial prevention','Primary prevention','Secondary prevention','Tertiary prevention'],ci:1,r:'Providing supplementation to prevent a specific disease before it occurs is primary prevention — specifically specific protection. Iron supplementation prevents iron deficiency anemia in pregnant women.'},
{s:'np1',t:'Levels of Prevention',q:'A community nurse conducts a newborn screening program. This represents which level of prevention?',c:['Primary prevention — health promotion','Primary prevention — specific protection','Secondary prevention — early case detection','Tertiary prevention — rehabilitation'],ci:2,r:'Newborn screening for metabolic disorders represents early case detection — secondary prevention. It identifies disease in its asymptomatic stage when treatment is most effective.'},
{s:'np1',t:'Levels of Prevention',q:'Government policies banning smoking in public places is an example of:',c:['Health promotion','Specific protection','Primordial prevention','Early diagnosis'],ci:2,r:'Primordial prevention involves actions to prevent the establishment of risk factors through social and environmental policies. Banning smoking prevents the social norm of smoking — addressing the risk factor itself before it develops.'},
{s:'np1',t:'Levels of Prevention',q:'A patient who had a stroke undergoes speech therapy. This is an example of:',c:['Primary prevention','Secondary prevention','Disability limitation','Rehabilitation'],ci:3,r:'Rehabilitation is the second level of tertiary prevention. It aims to restore function and maximize independence after disease has occurred. Speech therapy after stroke helps restore lost communicative function.'},
{s:'np1',t:'Levels of Prevention',q:'According to Leavell and Clark, which level of prevention includes early diagnosis and prompt treatment?',c:['Primary prevention','Secondary prevention','Tertiary prevention','Primordial prevention'],ci:1,r:'Secondary prevention includes early diagnosis and prompt treatment to halt disease progression, prevent spread, and reduce complications. Examples include tuberculosis case finding and cancer screening programs.'},
{s:'np1',t:'Family Nursing',q:'According to the typology of family nursing problems, an uncontrolled diabetic condition in a family member is classified as:',c:['Health threat','Health deficit','Foreseeable crisis','Stress point'],ci:1,r:'A health deficit is failure in health maintenance — actual disease or disability that has already occurred. An uncontrolled diabetic condition is an example. Health threats are risk factors that may lead to disease.'},
{s:'np1',t:'Family Nursing',q:'The FIRST step in the family nursing process is:',c:['Setting health goals with the family','Identifying family health problems','Collecting family health data','Evaluating outcomes of care'],ci:2,r:'Like the individual nursing process, family nursing begins with data collection — gathering comprehensive information about the family structure, dynamics, health status, and resources.'},
{s:'np1',t:'Family Nursing',q:'A family says their hypertensive member does not need treatment because they feel fine. This reflects which family nursing problem?',c:['Inability to make decisions about appropriate health action','Failure to recognize the presence of the health condition','Inability to provide adequate care','Failure to utilize community resources'],ci:0,r:'The family demonstrates inability to make decisions about appropriate health action — they recognize hypertension exists but fail to appreciate its seriousness. The nurse must help the family understand the consequences of untreated hypertension.'},
{s:'np1',t:'Family Nursing',q:'In family-centered nursing care, the family is viewed as:',c:['Only the mother and children','A system where health of one member affects all','Individual members treated separately','Only the sick member'],ci:1,r:'In community health nursing, the family is viewed as a system — health problems of one member affect all others. Care is directed at the family as a whole unit, addressing interactions, roles, and shared environment.'},
{s:'np1',t:'Family Nursing',q:'The nurse identifies that a family cannot afford the prescribed medications. This is classified as:',c:['Health deficit','Health threat','Failure to utilize community resources','Foreseeable crisis'],ci:2,r:'Failure to utilize community resources refers to the family\'s inability or failure to access available health services, programs, or assistance. The nurse should link the family to financial assistance programs like PhilHealth or Malasakit Center.'},
{s:'np1',t:'Immunization',q:'The BCG vaccine is given to newborns primarily to protect against:',c:['All forms of tuberculosis','Severe forms of TB such as TB meningitis and miliary TB','Pulmonary tuberculosis in adults','Hepatitis B infection'],ci:1,r:'BCG (Bacillus Calmette-Guerin) primarily protects against severe, disseminated forms of tuberculosis in children — particularly TB meningitis and miliary TB. It does not reliably prevent pulmonary TB in adults.'},
{s:'np1',t:'Immunization',q:'According to the Philippine Expanded Program on Immunization (EPI), the Hepatitis B vaccine should be given at birth within:',c:['12 hours','24 hours','48 hours','72 hours'],ci:1,r:'The HBV birth dose should be given within 24 hours of birth to prevent perinatal transmission from HBV-positive mothers. This is critical because babies born to infected mothers have a 90% chance of developing chronic hepatitis B if not vaccinated promptly.'},
{s:'np1',t:'Immunization',q:'A child received the first dose of DPT vaccine at 6 weeks. When should the second dose be given?',c:['8 weeks','10 weeks','12 weeks','16 weeks'],ci:1,r:'The DPT vaccine is given at 6, 10, and 14 weeks per the Philippine EPI schedule (minimum 4-week intervals). The second dose at 10 weeks follows the 4-week minimum interval from the first dose at 6 weeks.'},
{s:'np1',t:'Immunization',q:'Which of the following vaccines requires a cold chain temperature of -15 to -25 degrees Celsius?',c:['DPT vaccine','BCG vaccine','OPV (Oral Polio Vaccine)','Hepatitis B vaccine'],ci:2,r:'OPV (Oral Polio Vaccine) requires the coldest storage temperature (-15 to -25°C) because it is a live attenuated vaccine most sensitive to heat. Breaking the cold chain destroys the vaccine\'s potency.'},
{s:'np1',t:'Immunization',q:'Herd immunity is most effective when what percentage of the population is immune?',c:['50-60%','70-75%','80-95% depending on the disease','100%'],ci:2,r:'Herd immunity thresholds vary by disease — measles requires 92-95%, polio requires 80-85%, and pertussis requires 92-94% population immunity. When enough people are immune, susceptible individuals are indirectly protected because disease cannot spread easily.'},
{s:'np1',t:'Immunization',q:'A mother refuses to have her child vaccinated due to religious beliefs. The most appropriate nursing action is to:',c:['Force the vaccination for the child\'s safety','Document refusal and report to authorities','Provide education about vaccine benefits and risks, respect decision, ensure safety net','Skip the visit and return another time'],ci:2,r:'The nurse should provide thorough health education about benefits and risks of immunization, respect the family\'s autonomous decision, and document the informed refusal. The nurse can offer alternative appointments and ensure the child is monitored for vaccine-preventable diseases.'},
{s:'np1',t:'Tuberculosis',q:'According to the Philippine NTP (National Tuberculosis Program), the standard treatment for new smear-positive pulmonary TB is:',c:['3 months HRZE followed by 3 months HR','2 months HRZE followed by 4 months HR','6 months of isoniazid only','12 months of isoniazid and rifampicin'],ci:1,r:'The standard TB regimen in the Philippines is 2HRZE/4HR — 2 months intensive phase (isoniazid, rifampicin, pyrazinamide, ethambutol) followed by 4 months continuation phase (isoniazid, rifampicin). Total treatment is 6 months.'},
{s:'np1',t:'Tuberculosis',q:'Which anti-TB drug is associated with orange-red discoloration of urine and body secretions?',c:['Isoniazid','Ethambutol','Rifampicin','Pyrazinamide'],ci:2,r:'Rifampicin causes harmless orange-red discoloration of urine, sweat, tears, and other body secretions. Patients should be counseled about this expected side effect to prevent unnecessary alarm or discontinuation of treatment.'},
{s:'np1',t:'Tuberculosis',q:'A patient on anti-TB drugs develops visual disturbances and color blindness. Which drug is most likely responsible?',c:['Isoniazid','Ethambutol','Rifampicin','Pyrazinamide'],ci:1,r:'Ethambutol causes optic neuritis manifested by visual disturbances, decreased visual acuity, and red-green color blindness. Visual acuity and color discrimination should be assessed monthly in patients taking ethambutol.'},
{s:'np1',t:'Tuberculosis',q:'Directly Observed Treatment (DOT) in TB management means:',c:['The patient takes medications at home without supervision','A health worker observes the patient swallow every dose of medication','The patient is observed through a camera while taking medications','Medications are delivered to the patient\'s home'],ci:1,r:'DOT requires a designated health worker (treatment partner) to physically observe the patient swallow every dose of anti-TB medication. This ensures adherence, prevents drug resistance, and is the cornerstone of the DOTS strategy.'},
{s:'np1',t:'Tuberculosis',q:'A patient who stops taking TB medications for more than 2 months is classified as:',c:['Treatment failed','Defaulter','Relapse','Transfer out'],ci:1,r:'A defaulter is a TB patient who interrupts treatment for 2 or more consecutive months. Defaulters are at risk for developing drug-resistant TB and require careful re-evaluation and re-registration before resuming treatment.'},
{s:'np1',t:'Maternal and Child Health',q:'The recommended interval between prenatal visits for a low-risk pregnant woman in the Philippines is:',c:['Every week throughout pregnancy','Monthly until 28 weeks, then every 2 weeks until 36 weeks, then weekly','Every 2 weeks throughout pregnancy','Every month throughout pregnancy'],ci:1,r:'WHO and Philippine DOH recommend at least 8 antenatal care contacts: monthly until 28 weeks, every 2 weeks from 28-36 weeks, then weekly from 36 weeks to delivery. This ensures comprehensive monitoring of maternal and fetal well-being.'},
{s:'np1',t:'Maternal and Child Health',q:'The Philippine program that provides free maternal care services to indigent mothers is called:',c:['Malasakit Center','PhilHealth Maternity Package','MNCHN Strategy','Garantisadong Pambata'],ci:2,r:'The MNCHN (Maternal, Neonatal, Child Health and Nutrition) Strategy provides comprehensive maternal and child health services through the DOH. It aims to reduce maternal, neonatal, and under-5 mortality through an integrated continuum of care.'},
{s:'np1',t:'Maternal and Child Health',q:'Which of the following is a danger sign during pregnancy that requires IMMEDIATE referral?',c:['Mild ankle edema in the afternoon','Occasional mild heartburn','Vaginal bleeding at any time during pregnancy','Increased frequency of urination in first trimester'],ci:2,r:'Any vaginal bleeding during pregnancy is a danger sign requiring immediate medical evaluation. It may indicate placenta previa, abruptio placentae, or threatened abortion — all potentially life-threatening to mother and fetus.'},
{s:'np1',t:'Maternal and Child Health',q:'The purpose of vitamin A supplementation given to postpartum mothers within 4 weeks of delivery is to:',c:['Prevent postpartum hemorrhage','Provide vitamin A to the infant through breast milk','Prevent postpartum depression','Promote faster uterine involution'],ci:1,r:'Postpartum vitamin A supplementation (200,000 IU single dose) replenishes maternal vitamin A stores and increases the concentration of vitamin A in breast milk, providing protection against vitamin A deficiency to the breastfeeding infant.'},
{s:'np1',t:'Maternal and Child Health',q:'The IMCI (Integrated Management of Childhood Illness) approach classifies a child as having SEVERE PNEUMONIA if:',c:['Respiratory rate is 40 breaths per minute or more','Respiratory rate is 50 breaths per minute or more with chest indrawing','The child has chest indrawing or stridor','The child has fever above 38.5°C'],ci:2,r:'According to IMCI, severe pneumonia in a child 2 months to 5 years is classified by chest indrawing (lower chest wall caves in with breathing) or stridor. Fast breathing alone without chest indrawing is classified as pneumonia (not severe).'},
{s:'np1',t:'Nutrition',q:'The Philippine Nutrition Program classifies a child as SEVERELY WASTED if the weight-for-height z-score is:',c:['Below -1 SD','Below -2 SD','Below -3 SD','Below -4 SD'],ci:2,r:'Severe acute malnutrition (severe wasting) is defined as weight-for-height z-score below -3 SD, or MUAC less than 115mm, or the presence of bilateral pitting edema. This requires urgent therapeutic feeding intervention.'},
{s:'np1',t:'Nutrition',q:'The recommended duration of EXCLUSIVE breastfeeding according to WHO and DOH Philippines is:',c:['3 months','4 months','6 months','12 months'],ci:2,r:'WHO and Philippine DOH recommend exclusive breastfeeding (breast milk only, no water, other liquids, or solids) for the first 6 months of life. Complementary foods should then be introduced while continuing breastfeeding up to 2 years or beyond.'},
{s:'np1',t:'Nutrition',q:'Iodine deficiency during pregnancy most critically leads to:',c:['Maternal hypertension','Cretinism in the newborn','Gestational diabetes','Placenta previa'],ci:1,r:'Severe iodine deficiency during pregnancy causes cretinism in the newborn — characterized by intellectual disability, deafness, and growth failure. Iodine is essential for thyroid hormone production which is critical for fetal brain development.'},
{s:'np1',t:'Nutrition',q:'The nutritional program in the Philippines that provides supplementary feeding to malnourished children is:',c:['Garantisadong Pambata','Operation Timbang Plus','Pinggang Pinoy','Supplementary Feeding Program'],ci:3,r:'The Supplementary Feeding Program (SFP) provides nutrient-dense food supplements to malnourished children 6 months to below 5 years in day care centers. Operation Timbang Plus is the nutrition assessment/monitoring program.'},
{s:'np1',t:'Nutrition',q:'Vitamin A deficiency in children can lead to:',c:['Rickets','Scurvy','Night blindness and xerophthalmia','Pellagra'],ci:2,r:'Vitamin A deficiency causes night blindness (inability to see in dim light) and xerophthalmia (dry eyes, Bitot\'s spots, corneal ulceration). Severe deficiency can cause blindness. The Philippines gives Vitamin A supplements to children 6-71 months twice yearly.'},
{s:'np1',t:'Home Visit',q:'The PRIMARY purpose of a home visit by a community health nurse is to:',c:['Conduct physical examination of sick family members','Provide nursing care in the natural environment of the family','Report family conditions to the barangay captain','Collect environmental samples for testing'],ci:1,r:'The primary purpose of a home visit is to provide nursing care in the family\'s natural environment, allowing assessment of the home setting, family dynamics, and health practices in their actual context — enabling more realistic and effective interventions.'},
{s:'np1',t:'Home Visit',q:'During a home visit, the nurse finds that a family is unable to care for a sick elderly member. The nurse should FIRST:',c:['Report to social welfare for institutionalization','Assess the family\'s specific barriers and capabilities','Demonstrate all nursing procedures immediately','Refer to a hospital for admission'],ci:1,r:'Assessment always comes first. The nurse must identify the specific reasons why the family cannot provide care — whether knowledge deficit, lack of skills, financial constraints, or physical limitations — before planning appropriate interventions.'},
{s:'np1',t:'Home Visit',q:'Which of the following is the CORRECT sequence of a home visit?',c:['Greeting — assessment — care — teaching — recording','Initiation — pre-visit preparation — home visit — post-visit activities','Introduction — assessment — intervention — evaluation — documentation','Assessment — planning — implementation — evaluation'],ci:1,r:'The correct sequence of a community health nursing home visit follows: Initiation (identifying the family) — Pre-visit preparation (reviewing records, planning) — Home visit (assessment, care, teaching) — Post-visit activities (recording, reporting, follow-up planning).'},
{s:'np1',t:'School Health',q:'The school health program in the Philippines is jointly implemented by:',c:['DOH and DSWD','DepEd and DOH','LGU and DepEd','DOH and LGU'],ci:1,r:'The School Health and Nutrition Program is jointly implemented by the Department of Education (DepEd) and Department of Health (DOH). DepEd provides the setting and personnel while DOH provides health standards, technical guidance, and health services.'},
{s:'np1',t:'School Health',q:'A school nurse finds a student with pediculosis capitis (head lice). The most appropriate action is to:',c:['Send the student home immediately','Treat the student in school and notify parents','Notify parents, exclude the student until treated, and educate about prevention','Report to the barangay health center only'],ci:2,r:'The management of pediculosis includes: notifying parents, excluding the student from school until effectively treated, treating all household contacts, and health education about transmission and prevention. Return to school is allowed after treatment.'},
{s:'np1',t:'Occupational Health',q:'The primary role of an occupational health nurse is:',c:['Treating occupational diseases in the hospital','Preventing work-related illnesses and injuries through hazard assessment and health promotion','Conducting laboratory tests for employees','Managing the company health insurance'],ci:1,r:'The occupational health nurse\'s primary role is prevention — identifying workplace hazards, implementing safety measures, providing pre-employment and periodic health examinations, and promoting worker health and wellness to prevent work-related diseases and injuries.'},
{s:'np1',t:'Occupational Health',q:'The "hierarchy of controls" in occupational health, listed from MOST to LEAST effective, is:',c:['PPE — engineering controls — administrative controls — substitution — elimination','Elimination — substitution — engineering controls — administrative controls — PPE','Administrative controls — PPE — engineering controls — substitution — elimination','Engineering controls — elimination — substitution — PPE — administrative controls'],ci:1,r:'The hierarchy of hazard controls from most to least effective: Elimination (remove hazard) — Substitution (replace with safer alternative) — Engineering controls (isolate people from hazard) — Administrative controls (change work practices) — PPE (protect workers from hazard).'},
{s:'np1',t:'Disaster Nursing',q:'In the START (Simple Triage and Rapid Treatment) system, a patient who is breathing but has a respiratory rate of 32 breaths/minute is tagged:',c:['Green (minor)','Yellow (delayed)','Red (immediate)','Black (deceased/expectant)'],ci:2,r:'In START triage, a respiratory rate greater than 30 breaths/minute after airway positioning tags the patient as RED (immediate). This indicates critical respiratory compromise requiring immediate intervention.'},
{s:'np1',t:'Disaster Nursing',q:'During a mass casualty event, which patient should be triaged as BLACK (expectant)?',c:['A conscious patient with a broken leg','A patient who is not breathing even after airway repositioning','A patient breathing at 28 breaths/minute with a radial pulse','A patient with multiple lacerations who is alert'],ci:1,r:'In START triage, a patient who is not breathing after airway repositioning is tagged BLACK (deceased/expectant). Resources are focused on salvageable patients. Resuscitation efforts during mass casualties are typically not performed on apneic patients.'},
{s:'np1',t:'Disaster Nursing',q:'The PICE (Philippine Institute of Civil Engineers) recommends which evacuation priority during disaster?',c:['Strong men first, then women and children','Children, elderly, PWDs, and pregnant women first','Healthcare workers first to set up medical posts','Everyone evacuates at the same time'],ci:1,r:'During evacuation, priority is given to the most vulnerable populations: children, elderly, persons with disabilities (PWDs), pregnant women, and the sick. These groups have greater difficulty with self-evacuation and are at higher risk for harm.'},
{s:'np1',t:'DOH Programs',q:'The Universal Health Care Act (RA 11223) mandates that all Filipinos are automatically enrolled in:',c:['DSWD financial assistance','PhilHealth','Malasakit Center','Senior Citizens Program'],ci:1,r:'RA 11223 or the Universal Health Care Act mandates automatic PhilHealth enrollment for all Filipinos, ensuring access to comprehensive health services. The law shifts PhilHealth from employment-based to citizenship-based coverage.'},
{s:'np1',t:'DOH Programs',q:'The DOH program that provides essential newborn care practices — drying, skin-to-skin contact, early breastfeeding, and delayed cord clamping — is called:',c:['Mother-Baby Friendly Hospital Initiative','Unang Yakap (Essential Intrapartum and Newborn Care)','Garantisadong Pambata','MNCHN Strategy'],ci:1,r:'Unang Yakap (First Embrace) or EINC (Essential Intrapartum and Newborn Care) is the DOH program mandating four core newborn care practices: immediate drying, skin-to-skin contact, early initiation of breastfeeding, and appropriately timed cord clamping.'},
{s:'np1',t:'DOH Programs',q:'The Philippine program that provides free medicines, medical supplies, and financial assistance to indigent patients in public hospitals through a one-stop-shop is:',c:['PhilHealth','4Ps Program','Malasakit Center','DSWD Assistance'],ci:2,r:'The Malasakit Center (RA 11463) is a one-stop-shop where indigent patients can access assistance from DOH (free medicines), DSWD (financial assistance), PCSO (medical assistance), and PhilHealth simultaneously without going to multiple offices.'},
];
async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} NP1 questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
