const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
{s:'np3',t:'Fundamentals of Nursing',q:'If a nurse administers an injection to a patient who refuses that injection, she has committed:',c:['Assault and battery','Negligence','Malpractice','None of the above'],ci:0,r:'Assault is the unjustifiable attempt or threat to touch or injure another person. Battery is the unlawful touching of another person or the carrying out of threatened physical harm. Any act that a nurse performs on the patient against his will is considered assault and battery.'},
{s:'np3',t:'Fundamentals of Nursing',q:'All of the following can cause tachycardia EXCEPT:',c:['Fever','Exercise','Sympathetic nervous system stimulation','Parasympathetic nervous system stimulation'],ci:3,r:'Parasympathetic nervous system stimulation decreases the heart rate as well as the force of contraction. Fever, exercise, and sympathetic stimulation all increase the heart rate.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The absence of which pulse may not be a significant finding when a patient is admitted to the hospital?',c:['Apical','Radial','Pedal','Femoral'],ci:2,r:'Because the pedal pulse cannot be detected in 10% to 20% of the population, its absence is not necessarily a significant finding. The presence or absence of the pedal pulse should be documented upon admission so that changes can be identified during the hospital stay.'},
{s:'np3',t:'Fundamentals of Nursing',q:'When a patient in the terminal stages of lung cancer begins to exhibit loss of consciousness, a major nursing priority is to:',c:['Protect the patient from injury','Insert an airway','Elevate the head of the bed','Withdraw all pain medications'],ci:0,r:'Ensuring the patient safety is the most essential action at this time. The other nursing actions may be necessary but are not a major priority.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following procedures always requires surgical asepsis?',c:['Vaginal instillation of conjugated estrogen','Urinary catheterization','Nasogastric tube insertion','Colostomy irrigation'],ci:1,r:'The urinary system is normally free of microorganisms except at the urinary meatus. Any procedure that involves entering this system must use surgically aseptic measures to maintain a bacteria-free state.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following constitutes a break in sterile technique while preparing a sterile field for a dressing change?',c:['Using sterile forceps rather than sterile gloves to handle a sterile item','Touching the outside wrapper of sterilized material without sterile gloves','Placing a sterile object on the edge of the sterile field','Pouring out a small amount of solution before pouring the solution into a sterile container'],ci:2,r:'The edges of a sterile field are considered contaminated. When sterile items are allowed to come in contact with the edges of the field, the sterile items also become contaminated.'},
{s:'np3',t:'Fundamentals of Nursing',q:'When removing a contaminated gown, the nurse should be careful that the first thing she touches is the:',c:['Waist tie and neck tie at the back of the gown','Waist tie in front of the gown','Cuffs of the gown','Inside of the gown'],ci:0,r:'The back of the gown is considered clean, the front is contaminated. After removing gloves and washing hands, the nurse should untie the back of the gown; slowly move backward away from the gown, holding the inside of the gown and keeping the edges off the floor; turn and fold the gown inside out; discard it in a contaminated linen container; then wash hands again.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following nursing interventions is considered the most effective form of universal precautions?',c:['Cap all used needles before removing them from their syringes','Discard all used uncapped needles and syringes in an impenetrable protective container','Wear gloves when administering IM injections','Follow enteric precautions'],ci:1,r:'Blood-to-blood contact occurs most commonly when a health care worker attempts to recap a used needle. Therefore, used needles should never be recapped; instead they should be inserted in a specially designed puncture resistant, labeled container.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following blood tests should be performed before a blood transfusion?',c:['Prothrombin and coagulation time','Blood typing and cross-matching','Bleeding and clotting time','Complete blood count and electrolyte levels'],ci:1,r:'Before a blood transfusion is performed, the blood of the donor and recipient must be checked for compatibility. Blood typing determines the ABO blood group and Rh factor. Cross-matching ensures that the donor and recipient blood are compatible.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The primary purpose of a platelet count is to evaluate the:',c:['Potential for clot formation','Potential for bleeding','Presence of an antigen-antibody response','Presence of cardiac enzymes'],ci:1,r:'Platelets are disk-shaped cells that are essential for blood coagulation. A platelet count determines the number of thrombocytes in blood available for promoting hemostasis and assisting with blood coagulation after injury. A count of 100,000/mm3 or less indicates a potential for bleeding.'},
{s:'np3',t:'Fundamentals of Nursing',q:'After 7 days of diuretic therapy, a patient begins to exhibit muscle cramping and muscle weakness. These symptoms probably indicate that the patient is experiencing:',c:['Hypokalemia','Hyperkalemia','Anorexia','Dysphagia'],ci:0,r:'Fatigue, muscle cramping, and muscle weakness are symptoms of hypokalemia (an inadequate potassium level), which is a potential side effect of diuretic therapy. The physician usually orders supplemental potassium to prevent hypokalemia in patients receiving diuretics.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following statements about chest X-ray is false?',c:['No contradictions exist for this test','Before the procedure, the patient should remove all jewelry, metallic objects, and buttons above the waist','A signed consent is not required','Eating, drinking, and medications are allowed before this test'],ci:0,r:'Pregnancy is the only contraindication for a chest X-ray. However, if a chest X-ray is necessary, the patient can wear a lead apron shield to protect the fetus. A signed consent is not required. The patient may eat, drink, and take medications before the test.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The most appropriate time for the nurse to obtain a sputum specimen for culture is:',c:['Early in the morning','After the patient eats a light breakfast','After aerosol therapy','After chest physiotherapy'],ci:0,r:'The first morning specimen is optimal because secretions that accumulate during sleep contain the highest concentration of organisms. The patient should rinse the mouth before coughing to remove food particles and reduce contamination of the specimen.'},
{s:'np3',t:'Fundamentals of Nursing',q:'A patient with no known allergies is to receive penicillin every 6 hours. When administering the medication, the nurse observes a fine rash on the patient skin. The most appropriate nursing action would be to:',c:['Withhold the medication and notify the physician','Administer the medication and notify the physician','Administer the medication with an antihistamine','Apply corn starch soaks to the rash'],ci:0,r:'A rash can be an allergic reaction to the drug. Although a rash is not serious in itself, it could be an early sign of anaphylaxis. Therefore, the nurse should withhold the drug and notify the physician immediately.'},
{s:'np3',t:'Fundamentals of Nursing',q:'All of the following nursing interventions are correct when using the Z-track method of drug injection EXCEPT:',c:['Prepare the injection site with alcohol','Use a needle that is at least 1 inch long','Aspirate for blood before injection','Rub the site vigorously after the injection to promote absorption'],ci:3,r:'The site should NOT be rubbed after Z-track injection. Rubbing could cause the medication to seep up through the track and irritate subcutaneous tissue. The Z-track method is used to prevent tracking of the medication through the subcutaneous tissue.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The correct method for determining the vastus lateralis site for IM injection is to:',c:['Locate the upper aspect of the upper outer quadrant of the buttock about 5 to 8 cm below the iliac crest','Palpate the lower edge of the acromion process and the midpoint lateral aspect of the arm','Palpate a 1 inch circular area anterior to the umbilicus','Divide the area between the greater femoral trochanter and the lateral femoral condyle into thirds and select the middle third on the anterior of the thigh'],ci:3,r:'The vastus lateralis is located on the anterior lateral aspect of the thigh. The area between the greater trochanter of the femur and the lateral femoral condyle is divided into thirds, and the injection is given in the middle third. This site is preferred in infants and small children.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The appropriate needle size for insulin injection is:',c:['18G, 1.5 inch long','22G, 1 inch long','22G, 1.5 inch long','25G, 5/8 inch long'],ci:3,r:'A 25G, 5/8 inch needle is the recommended size for insulin injection because insulin is administered by the subcutaneous route. An 18G, 1.5 inch needle is usually used for IM injections into the vastus lateralis.'},
{s:'np3',t:'Fundamentals of Nursing',q:'To assess kidney function of a patient with an indwelling urinary Foley catheter, the nurse measures his hourly urine output. She should notify the physician if the urine output is:',c:['Less than 30 ml/hour','54 ml in 2 hours','90 ml in 3 hours','120 ml in 4 hours'],ci:0,r:'A urine output of less than 30ml/hour indicates hypovolemia or oliguria, which is related to kidney function and inadequate fluid intake.'},
{s:'np3',t:'Fundamentals of Nursing',q:'A male patient who had surgery 2 days ago for head and neck cancer is about to make his first attempt to ambulate outside his room. The nurse notes that he is steady on his feet and his vision was unaffected by the surgery. Which nursing intervention would be appropriate?',c:['Encourage the patient to walk in the hall alone','Discourage the patient from walking in the hall for a few more days','Accompany the patient for his walk','Consult a physical therapist before allowing the patient to ambulate'],ci:2,r:'Even if the patient appears steady, the nurse should accompany the patient on his first ambulation outside the room to ensure his safety and provide support as needed.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Mrs Lim begins to cry as the nurse discusses hair loss. The best response would be:',c:["Don't worry. It's only temporary!","Why are you crying? I didn't get to the bad news yet!",'Your hair is really pretty!','I know this will be difficult for you, but your hair will grow back after the completion of chemotherapy!'],ci:3,r:'Acknowledging the patient\'s feelings and providing accurate information is the most therapeutic response. This response validates the patient\'s concern and provides hope while being honest about the situation.'},
{s:'np3',t:'Fundamentals of Nursing',q:'After 1 week of hospitalization, Mr Gray develops hypokalemia. Which of the following is the most significant symptom of his disorder?',c:['Lethargy','Increased pulse rate and blood pressure','Muscle weakness','Muscle irritability'],ci:2,r:'Hypokalemia causes muscle weakness because potassium is essential for proper neuromuscular function. In severe hypokalemia, paralysis and respiratory failure can occur. ECG changes including flat or inverted T waves are also significant.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following nursing interventions promotes patient safety?',c:["Assess the patient's ability to ambulate and transfer from a bed to a chair",'Demonstrate the signal system to the patient','Check to see that the patient is wearing his identification band','All of the above'],ci:3,r:'All of the identified nursing interventions promote patient safety. Assessing ambulation ability prevents falls, demonstrating call system allows the patient to summon help, and checking identification bands ensures proper patient identification.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The most common injury among elderly persons is:',c:['Atherosclerotic changes in the blood vessels','Increased incidence of gallbladder disease','Urinary Tract Infection','Hip fracture'],ci:3,r:'Hip fracture is the most common injury among elderly persons due to osteoporosis and increased fall risk. Falls in the elderly are often related to decreased muscle strength, balance problems, medication side effects, and environmental hazards.'},
{s:'np3',t:'Fundamentals of Nursing',q:'The most common psychogenic disorder among elderly persons is:',c:['Depression','Sleep disturbances such as bizarre dreams','Inability to concentrate','Decreased appetite'],ci:0,r:'Depression is the most common psychogenic disorder among elderly persons, affecting up to 15% of community-dwelling elderly and higher rates in institutionalized settings. It is often underdiagnosed and undertreated in this population.'},
{s:'np3',t:'Fundamentals of Nursing',q:'Which of the following is the most common cause of dementia among elderly persons?',c:["Parkinson's disease",'Multiple sclerosis','Amyotrophic lateral sclerosis (Lou Gehrig\'s disease)',"Alzheimer's disease"],ci:3,r:"Alzheimer's disease is the most common cause of dementia, accounting for 60-80% of all cases. It is characterized by progressive memory loss, cognitive decline, and behavioral changes. Vascular dementia is the second most common cause."},
{s:'np3',t:'Fundamentals of Nursing',q:"The nurse's most important legal responsibility after a patient's death in a hospital is:",c:['Obtaining a consent of an autopsy','Notifying the coroner or medical examiner','Labeling the corpse appropriately','Ensuring that the attending physician issues the death certification'],ci:2,r:'After a patient dies, proper identification of the body is the nurse\'s primary responsibility. The corpse must be labeled appropriately with the patient\'s name, room number, and hospital identification number before transfer to the morgue.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client diagnosed with angina pectoris is given nitroglycerin to relieve chest pain. The nurse explains to the client that nitroglycerin relieves angina because it:',c:['Increases the oxygen carrying capacity of the blood','Increases the strength of cardiac contractions','Decreases the heart rate and dilates the coronary arteries','Reduces ventricular irritability'],ci:2,r:'Nitroglycerin relieves angina by dilating the coronary arteries, which increases blood flow to the myocardium, and by reducing preload through venodilation. These actions decrease myocardial oxygen demand and increase oxygen supply.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with hypertension is prescribed a low-sodium diet. Which of the following foods should be avoided?',c:['Fresh fruits and vegetables','Whole grain bread and cereals','Processed meats and canned soups','Plain rice and pasta'],ci:2,r:'Processed meats, canned soups, and other preserved foods are high in sodium. Fresh fruits and vegetables, whole grains, and plain starches are low in sodium and appropriate for a low-sodium diet.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with chronic obstructive pulmonary disease COPD is receiving oxygen therapy. The nurse understands that the appropriate flow rate of oxygen is:',c:['6 to 10 L/min','4 to 6 L/min','2 to 3 L/min','10 to 15 L/min'],ci:2,r:'COPD clients retain CO2 and rely on hypoxic drive for respiration. High flow oxygen can eliminate the hypoxic drive and cause respiratory depression. Therefore, low-flow oxygen (1-3 L/min via nasal cannula) is appropriate.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with diabetes mellitus is scheduled for surgery. Preoperatively, the nurse should be most concerned about which of the following?',c:['Fluid and electrolyte imbalances','Wound healing complications','Hypoglycemia from NPO status','All of the above'],ci:3,r:'Diabetic clients are at risk for multiple perioperative complications including fluid and electrolyte imbalances from osmotic diuresis, delayed wound healing due to impaired circulation and immune function, and hypoglycemia from NPO status with continued insulin administration.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'When caring for a patient with a nasogastric tube, which nursing action is most important?',c:['Irrigate the tube with saline every 4 hours','Verify correct tube placement before each use','Keep the patient in semi-Fowlers position at all times','Change the tube every 48 hours'],ci:1,r:'Verifying correct NG tube placement before each feeding or medication administration is critical to prevent aspiration. Methods include checking gastric pH, aspirating gastric contents, and X-ray confirmation for initial placement.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client is admitted with acute myocardial infarction. Which of the following is the priority nursing action?',c:['Administer oxygen and relieve pain','Obtain a 12-lead ECG immediately','Establish IV access for medication administration','All of the above are equal priorities'],ci:0,r:'The immediate priority in MI is to restore oxygen supply to the myocardium and relieve pain (which increases oxygen demand). Oxygen therapy, pain relief with morphine, and aspirin administration are the immediate priorities in MI management.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client who has had a colostomy is being discharged. Which statement by the client indicates a need for further teaching?',c:["I will irrigate my colostomy at the same time each day","I should not swim or engage in contact sports","I can resume most of my normal activities","My diet does not need to be restricted"],ci:1,r:'Clients with a colostomy can swim and participate in most physical activities. The stoma is protected by the pouch. Contact sports may require extra precautions but are not generally prohibited. The client should be taught that most activities can be resumed.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'Following a thyroidectomy, the nurse should assess the client for signs of hypocalcemia which include:',c:['Muscle weakness and lethargy','Tetany, tingling, and muscle cramps','Elevated blood pressure and bradycardia','Increased reflexes and hypertension'],ci:1,r:'Hypocalcemia following thyroidectomy occurs due to inadvertent removal or damage to the parathyroid glands. Signs include tetany, tingling/numbness (paresthesias), and positive Chvostek and Trousseau signs. This is a surgical emergency requiring prompt treatment.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with peptic ulcer disease asks what foods to avoid. The nurse correctly advises the client to avoid:',c:['Milk and dairy products','Coffee, alcohol, and spicy foods','Fresh fruits and vegetables','Complex carbohydrates'],ci:1,r:'Coffee, alcohol, and spicy foods stimulate gastric acid secretion and should be avoided by clients with peptic ulcer disease. Milk was once recommended but is now known to stimulate acid production. Small frequent meals of bland foods are generally recommended.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with a chest tube drainage system. Which of the following findings indicates that the system is functioning properly?',c:['Continuous bubbling in the water-seal chamber','Intermittent bubbling in the suction control chamber','No fluctuation (tidaling) in the water-seal chamber','Drainage of more than 200 ml per hour'],ci:1,r:'Intermittent bubbling in the suction control chamber indicates that the suction is working properly. Continuous bubbling in the water-seal chamber indicates an air leak. Tidaling (fluctuation) in the water-seal chamber is normal. Drainage more than 200 ml/hr requires physician notification.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'Following a hip replacement, which position should be avoided to prevent prosthesis dislocation?',c:['Hip abduction with pillow between legs','Hip flexion greater than 90 degrees','Lying on the non-operative side','Partial weight bearing with walker'],ci:1,r:'After total hip replacement, hip flexion greater than 90 degrees must be avoided to prevent dislocation of the prosthesis. Other precautions include avoiding internal rotation and adduction (crossing the legs). These restrictions are maintained for several weeks post-surgery.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client receiving chemotherapy develops stomatitis. Which nursing intervention is most appropriate?',c:['Encourage the client to eat hot, spicy foods to stimulate appetite','Provide frequent mouth care with a soft toothbrush and saline rinses','Apply commercial mouthwash containing alcohol to kill bacteria','Restrict fluid intake to prevent mouth irritation'],ci:1,r:'Stomatitis (oral mucositis) from chemotherapy requires gentle oral hygiene. Soft toothbrush and saline rinses are recommended. Alcohol-containing mouthwashes should be avoided as they are drying and irritating. Frequent, gentle mouth care is essential.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with chronic renal failure is placed on a restricted diet. Which of the following nutrients is most commonly restricted?',c:['Carbohydrates','Protein and potassium','Vitamin C','Calcium'],ci:1,r:'In chronic renal failure, protein restriction reduces the production of nitrogenous waste products. Potassium restriction is needed because the failing kidneys cannot adequately excrete potassium, leading to dangerous hyperkalemia which can cause cardiac arrhythmias.'},
{s:'np3',t:'Medical-Surgical Nursing',q:'A client with increased intracranial pressure ICP is being positioned. Which position is most appropriate?',c:['Trendelenburg position','Head of bed flat','Head of bed elevated 30 degrees, head midline','Right lateral position'],ci:2,r:'Elevating the head of bed 30 degrees with the head in a neutral midline position promotes venous drainage from the brain, thereby reducing intracranial pressure. The Trendelenburg position and flat position increase ICP.'},
{s:'np2',t:'Maternal Nursing',q:'When assessing the adequacy of sperm for conception to occur, which of the following is the most useful criterion?',c:['Sperm count','Sperm motility','Sperm maturity','Semen volume'],ci:1,r:'Sperm motility (the ability of sperm to move forward progressively) is the most important factor for fertilization. Poor motility (asthenospermia) is a common cause of male infertility. While sperm count is important, motility is more critical for reaching and fertilizing the ovum.'},
{s:'np2',t:'Maternal Nursing',q:'Which of the following urinary symptoms does the pregnant woman most frequently experience during the first trimester?',c:['Dysuria','Frequency','Incontinence','Burning'],ci:1,r:'Urinary frequency is common in the first trimester due to the enlarging uterus pressing on the bladder and increased renal blood flow. This usually resolves in the second trimester as the uterus rises out of the pelvis, then returns in the third trimester.'},
{s:'np2',t:'Maternal Nursing',q:'Heartburn and flatulence, common in the second trimester, are most likely the result of which of the following?',c:['Increased plasma HCG levels','Decreased intestinal motility','Decreased gastric acidity','Elevated estrogen levels'],ci:1,r:'Decreased intestinal motility due to progesterone effects causes slower gastric emptying and increased transit time, leading to heartburn and flatulence. The pyloric sphincter relaxes, allowing gastric acid reflux. Small, frequent meals and avoiding spicy foods help manage these symptoms.'},
{s:'np2',t:'Maternal Nursing',q:'A pregnant client states that she "waddles" when she walks. The nurse explanation is based on which of the following as the cause?',c:['The large size of the newborn','Pressure on the pelvic muscles','Relaxation of the pelvic joints','Excessive weight gain'],ci:2,r:'The waddling gait of pregnancy is caused by relaxation of the symphysis pubis and sacroiliac joints due to the hormone relaxin. This pelvic joint relaxation, combined with the shift in center of gravity, causes the characteristic gait change.'},
{s:'np2',t:'Maternal Nursing',q:'Which of the following would cause a false-positive result on a pregnancy test?',c:['The test was performed less than 10 days after an abortion','The test was performed too early or too late in the pregnancy','The urine sample was stored too long at room temperature','A spontaneous abortion or a missed abortion is impending'],ci:0,r:'A false-positive pregnancy test can occur if performed less than 10 days after an abortion, as HCG levels remain elevated for 7-10 days after pregnancy termination. Other causes include choriocarcinoma and other HCG-producing tumors.'},
{s:'np2',t:'Maternal Nursing',q:'Fetal heart sounds can be auscultated with a fetoscope as early as which of the following?',c:['8 weeks gestation','10 weeks gestation','18 weeks gestation','20 weeks gestation'],ci:2,r:'Fetal heart tones can be heard with a fetoscope at 16-20 weeks gestation. With a Doppler device, FHT can be heard as early as 10-12 weeks. The normal FHR is 110-160 beats per minute.'},
{s:'np2',t:'Maternal Nursing',q:'Which of the following common emotional reactions to pregnancy would the nurse expect to occur during the first trimester?',c:['Introversion, egocentrism, narcissism','Awkwardness, clumsiness, and unattractiveness','Anxiety, passivity, extroversion','Ambivalence, fear, fantasies'],ci:3,r:'Ambivalence, fear, and fantasies are typical first trimester emotional responses. Even in a planned pregnancy, the reality of the situation can cause conflicting emotions. This is a normal part of adapting to the maternal role.'},
{s:'np2',t:'Maternal Nursing',q:'Which of the following would be a disadvantage of breast feeding?',c:['Involution occurs more rapidly','The incidence of allergies increases due to maternal antibodies','The father may resent the infant demands on the mother body','There is a greater chance for error during preparation'],ci:2,r:'While breastfeeding has many advantages for both mother and infant, some fathers may feel excluded or resentful of the close bond between mother and infant during breastfeeding. This is a potential psychosocial disadvantage that the nurse should address through anticipatory guidance.'},
{s:'np5',t:'Psychiatric Nursing',q:'A patient with schizophrenia is being discharged on haloperidol. The nurse should instruct the patient to:',c:['Take the medication only when experiencing hallucinations','Report any feelings of restlessness or agitation immediately','Discontinue the medication if side effects occur','Take the medication with antacids to prevent stomach upset'],ci:1,r:'Akathisia (motor restlessness) and agitation are extrapyramidal side effects of haloperidol that should be reported to the physician immediately. They can be treated with anticholinergic medications. Patients should never stop antipsychotics abruptly without physician guidance.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with depression is started on a tricyclic antidepressant. Which statement by the client indicates understanding of the medication?',c:['I will feel better within 2-3 days of starting this medication','It may take 2-4 weeks before I notice the full therapeutic effect','I should stop taking the medication when I feel better','I can drink alcohol in moderation while taking this medication'],ci:1,r:'Tricyclic antidepressants require 2-4 weeks to reach therapeutic blood levels and produce full antidepressant effects. Patients must be counseled about this delay to prevent premature discontinuation. Alcohol should be avoided as it potentiates CNS depression.'},
{s:'np5',t:'Psychiatric Nursing',q:'A nurse is caring for a client with anorexia nervosa. Which nursing intervention is most appropriate?',c:['Allow the client to decide when and what to eat','Weigh the client daily before breakfast','Stay with the client during meals and for 1 hour after eating','Encourage excessive exercise to promote appetite'],ci:2,r:'Staying with the client during meals and for 1 hour after eating prevents the client from disposing of food or purging. The nurse should sit with the client, offering support without focusing on eating behaviors. Weighing is done at consistent times but not necessarily daily.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with bipolar disorder in the manic phase is admitted. Which nursing intervention should receive the highest priority?',c:['Encourage participation in group activities','Ensure adequate nutrition and rest','Administer lithium as prescribed','Provide a structured environment with minimal stimulation'],ci:3,r:'During mania, clients are hyperactive, impulsive, and have poor judgment. A structured environment with minimal stimulation reduces sensory input and helps decrease manic behavior. Safety, nutrition, and sleep are immediate priorities in the manic phase.'},
{s:'np5',t:'Psychiatric Nursing',q:'A nurse is interviewing a client who demonstrates flight of ideas. This is characterized by:',c:['Repetition of the same word or phrase','Rapid shifting from one topic to another with loose connections','Making up words that have no meaning','Answering questions with unrelated responses'],ci:1,r:'Flight of ideas is characterized by rapid shifting from topic to topic, with connections between topics that may be understandable but are loose. It is commonly seen in bipolar disorder during manic episodes. It differs from loose associations in that some connection can usually be found.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with alcohol dependency is in withdrawal. Which medication is most commonly used for medical management?',c:['Haloperidol (Haldol)','Diazepam (Valium)','Lithium carbonate','Fluoxetine (Prozac)'],ci:1,r:'Benzodiazepines such as diazepam (Valium) are the drugs of choice for alcohol withdrawal because they prevent withdrawal seizures and delirium tremens. They act on GABA receptors similar to alcohol. Thiamine is also given to prevent Wernicke encephalopathy.'},
{s:'np5',t:'Psychiatric Nursing',q:'A nurse observes that a client with schizophrenia is responding to internal stimuli. The most appropriate nursing intervention is to:',c:['Leave the client alone to work through the hallucination','Calmly call the client by name and orient to reality','Argue with the client that the voices are not real','Ask the client to describe the content of the hallucinations'],ci:1,r:'Calmly calling the client by name and gently orienting to reality is the therapeutic approach for hallucinations. The nurse should acknowledge the client perception without reinforcing or arguing about the hallucination. The goal is to help the client focus on reality.'},
{s:'np5',t:'Psychiatric Nursing',q:'Which of the following nursing approaches is most therapeutic when establishing a relationship with a suspicious, paranoid client?',c:['Be very warm and friendly from the beginning','Use a matter-of-fact, consistent, and honest approach','Avoid making eye contact to reduce the client anxiety','Change care providers frequently to prevent attachment'],ci:1,r:'A consistent, honest, matter-of-fact approach builds trust with paranoid clients. Excessive warmth may be perceived as manipulation. Consistency from the same care providers reduces suspicion. The nurse should keep promises, be punctual, and explain all procedures.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with obsessive-compulsive disorder performs hand-washing rituals for 4-5 hours daily. The most appropriate nursing approach is to:',c:['Firmly prevent all hand-washing rituals','Allow the rituals while working to understand their meaning','Set strict time limits on all ritualistic behavior','Ignore the behavior completely'],ci:1,r:'The nurse should allow the ritual initially while working with the client to understand its function in managing anxiety. Abruptly preventing rituals increases anxiety to intolerable levels. The therapeutic goal is to gradually reduce rituals through desensitization and developing alternative coping strategies.'},
{s:'np5',t:'Psychiatric Nursing',q:'A suicidal client tells the nurse she feels better and no longer wants to die. The nurse is most concerned because:',c:['The client may be planning to harm someone else','Sudden improvement may indicate the client has made a plan to suicide','The client may be experiencing medication side effects','The improvement is genuine and the client is recovering'],ci:1,r:'Sudden improvement in a previously depressed, suicidal client is a warning sign, not a positive indicator. The improvement may indicate that the client has made a decision to act on suicidal plans and feels relief because the uncertainty is resolved. Vigilance must be maintained.'},
{s:'np5',t:'Psychiatric Nursing',q:'Which of the following behaviors indicates that a client with major depression is improving?',c:['Sleeping 18 hours per day','Making future plans','Withdrawing from group activities','Expressing hopelessness about the future'],ci:1,r:'Making future plans indicates that the client is beginning to see a future for themselves, which is a positive indicator of improvement in depression. Increased sleep, social withdrawal, and hopelessness are symptoms of depression that would indicate the client is not improving.'},
{s:'np5',t:'Psychiatric Nursing',q:'The nurse is caring for a client in alcohol withdrawal who develops delirium tremens DTs. Which assessment finding requires immediate intervention?',c:['Mild hand tremors','Elevated blood pressure and temperature','Visual hallucinations of insects','Seizures and loss of consciousness'],ci:3,r:'Seizures and loss of consciousness during delirium tremens represent the most life-threatening manifestation requiring immediate intervention. Benzodiazepines should be administered promptly and the physician notified immediately. DTs carry a mortality rate of 5-15% if untreated.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with a history of physical abuse is admitted to the psychiatric unit. Which nursing action should take priority?',c:['Provide crisis counseling','Ensure the client safety','Contact social services','Encourage the client to discuss the abusive relationship'],ci:1,r:'Safety is always the priority nursing concern for victims of abuse. Once safety is established, crisis counseling, social services referral, and therapeutic communication can be implemented. The nurse should assess for immediate danger and document injuries objectively.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client taking lithium carbonate asks why regular blood tests are required. The nurse correctly explains:',c:['To monitor kidney function only','To monitor the therapeutic blood level because the range between therapeutic and toxic doses is narrow','To check for infection caused by the medication','To ensure the medication is being absorbed properly'],ci:1,r:'Lithium has a narrow therapeutic window (0.6-1.2 mEq/L for maintenance). Blood levels must be monitored regularly because toxic levels can occur rapidly. Signs of toxicity include coarse tremors, confusion, vomiting, and can progress to seizures and death if not treated.'},
{s:'np5',t:'Psychiatric Nursing',q:'A client with post-traumatic stress disorder PTSD is experiencing flashbacks. The most appropriate nursing intervention is to:',c:['Leave the client alone until the flashback subsides','Restrain the client to prevent self-injury','Stay with the client, speaking calmly, and help orient to the present','Ask the client to stop thinking about the traumatic event'],ci:2,r:'During a flashback, the nurse should stay with the client, speak in a calm, reassuring voice, and help orient the client to the present time and place. The nurse should not restrain the client unless there is immediate danger. Asking the client to stop thinking about trauma is ineffective and invalidating.'},
{s:'np5',t:'Leadership and Management',q:'When delegating care to a licensed practical nurse LPN, the registered nurse RN must:',c:['Transfer full responsibility to the LPN for the delegated tasks','Remain accountable for the overall nursing care and supervision','Allow the LPN to independently decide what care to provide','Delegate all nursing assessments to the LPN'],ci:1,r:'Delegation does not transfer accountability. The RN remains accountable for the overall nursing care and must supervise the delegated tasks. The RN can delegate tasks that are within the LPN scope of practice but must provide appropriate direction and follow-up evaluation.'},
{s:'np5',t:'Professional Adjustment',q:'The Philippine Nursing Act (RA 9173) requires that nursing practice in the Philippines be:',c:['Performed only in hospitals and clinics','Guided by evidence-based practice and ethical standards','Limited to graduate nurses with advanced degrees','Supervised by physicians at all times'],ci:1,r:'RA 9173 or the Philippine Nursing Act of 2002 mandates that nursing practice be guided by evidence-based practice, ethical standards, and the Code of Ethics for Nurses. It establishes standards of nursing education and practice to ensure quality nursing care.'},
{s:'np1',t:'Community Health Nursing',q:'Which of the following best describes the primary focus of community health nursing?',c:['Providing care to acutely ill patients in the community','Preventing disease and promoting health of populations and communities','Treating chronic diseases in community settings','Providing home care to discharged hospital patients'],ci:1,r:'Community health nursing focuses on the health of populations and communities rather than individual patients. Primary prevention, health promotion, and disease prevention are the cornerstones of community health nursing practice.'},
{s:'np1',t:'Community Health Nursing',q:'The epidemiological triad consists of which of the following components?',c:['Host, agent, environment','Prevention, treatment, rehabilitation','Primary, secondary, tertiary prevention','Assessment, planning, implementation'],ci:0,r:'The epidemiological triad consists of the host (the person who gets the disease), the agent (the causative factor), and the environment (external factors that influence disease transmission). Understanding this triad helps identify risk factors and appropriate interventions.'},
{s:'np1',t:'Community Health Nursing',q:'Herd immunity is most effective in preventing the spread of communicable diseases when:',c:['All members of the community are immune','At least 80-90% of the population is immune','Only high-risk individuals are immunized','The most vulnerable groups are protected'],ci:1,r:'Herd immunity provides indirect protection to non-immune individuals when a sufficient proportion (typically 80-90% depending on the disease) of the community is immune. This reduces the probability of contact between susceptible and infected individuals.'},
{s:'np1',t:'Community Health Nursing',q:'In community health nursing, the nurse is conducting a community health assessment. Which is the FIRST step?',c:['Planning health interventions','Collecting data about the community','Evaluating health programs','Implementing health education'],ci:1,r:'Data collection and community assessment is always the first step in the community health nursing process. Before planning or implementing any intervention, the nurse must have comprehensive data about the community demographics, health status, resources, and needs.'},
];
async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} questions from R.C. Reña reviewer!`);
  } finally { client.release(); await pool.end(); }
}
seed().catch(console.error);
