const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
// CARDIOVASCULAR
{s:'np3',t:'Cardiac',q:'A client with heart failure is prescribed furosemide (Lasix). The nurse should monitor for which electrolyte imbalance?',c:['Hyperkalemia','Hypokalemia','Hypernatremia','Hypercalcemia'],ci:1,r:'Furosemide is a loop diuretic that causes potassium wasting. Hypokalemia is the most common electrolyte imbalance. Signs include muscle weakness, leg cramps, and cardiac dysrhythmias. Potassium supplementation is usually needed.'},
{s:'np3',t:'Cardiac',q:'A client with chronic heart failure has orthopnea. Which position is MOST appropriate?',c:['Flat supine','Prone','High Fowler\'s with legs dependent','Left lateral with one pillow'],ci:2,r:'High Fowler\'s position with legs dependent reduces venous return to the heart, decreases preload, and improves lung expansion. This relieves orthopnea (difficulty breathing when lying flat) by redistributing fluid away from the lungs.'},
{s:'np3',t:'Cardiac',q:'Which of the following is an early sign of digitalis toxicity?',c:['Hypertension','Bradycardia and nausea/vomiting','Tachycardia and dry mouth','Increased urinary output'],ci:1,r:'Early signs of digitalis toxicity include nausea, vomiting, anorexia, and bradycardia. Visual disturbances (yellow-green halos) are also classic. Hypokalemia potentiates toxicity. Hold the drug if HR is below 60 bpm and notify the physician.'},
{s:'np3',t:'Cardiac',q:'A client with atrial fibrillation is prescribed warfarin. The nurse knows the therapeutic INR range is:',c:['0.8-1.2','1.5-2.0','2.0-3.0','3.5-4.5'],ci:2,r:'The therapeutic INR range for atrial fibrillation anticoagulation is 2.0-3.0. Below 2.0 increases clot risk; above 3.0 increases bleeding risk. Regular INR monitoring is essential. Vitamin K reverses warfarin effects.'},
{s:'np3',t:'Cardiac',q:'A client reports chest pain radiating to the left arm, diaphoresis, and nausea. The PRIORITY nursing action is:',c:['Obtain a 12-lead ECG','Administer aspirin 325mg','Establish IV access','Apply oxygen and call for help'],ci:3,r:'The priority is to apply oxygen, call for help (activate the cardiac response team), and prepare for emergency interventions. Then administer aspirin, obtain ECG, establish IV access, and draw cardiac enzymes — all within the first 10 minutes.'},
{s:'np3',t:'Cardiac',q:'Which of the following indicates effective cardiopulmonary resuscitation (CPR) in an adult?',c:['Compressions at 60 per minute','Depth of 1 inch per compression','Rate of 100-120 compressions per minute with 2-inch depth','Ratio of 10:2 compressions to breaths'],ci:2,r:'Effective adult CPR requires compressions at 100-120 per minute, depth of at least 2 inches (5 cm), full chest recoil between compressions, and a ratio of 30:2 (compressions to breaths) for single rescuer. Minimize interruptions.'},
{s:'np3',t:'Myocardial Infarction',q:'A client with acute MI asks why morphine is given. The nurse correctly explains that morphine:',c:['Increases heart rate to improve cardiac output','Reduces pain, anxiety, and decreases myocardial oxygen demand','Dissolves blood clots in the coronary arteries','Strengthens cardiac contractions'],ci:1,r:'Morphine is given in MI for analgesia, anxiolysis, and vasodilation (reduces preload and afterload), which decreases myocardial oxygen demand. The mnemonic MONA (Morphine, Oxygen, Nitrates, Aspirin) guides initial MI management.'},
{s:'np3',t:'Myocardial Infarction',q:'Which cardiac enzyme is the MOST specific marker for myocardial infarction?',c:['LDH (lactate dehydrogenase)','AST (aspartate aminotransferase)','Troponin I or T','CK-MB (creatine kinase-MB)'],ci:2,r:'Troponin I and Troponin T are the most sensitive and specific markers for myocardial infarction. They rise within 3-6 hours, peak at 12-24 hours, and remain elevated for 7-14 days. CK-MB is also used but is less specific than troponin.'},
// RESPIRATORY
{s:'np3',t:'Respiratory',q:'A client with COPD is receiving oxygen. Which finding indicates oxygen-induced hypercapnia?',c:['Oxygen saturation of 95%','Decreased respiratory rate and increasing drowsiness','Restlessness and increased respiratory rate','Cyanosis of the lips'],ci:1,r:'COPD clients rely on hypoxic drive for respiration. High-flow oxygen removes the hypoxic stimulus, causing respiratory depression — decreased rate and drowsiness progressing to CO2 narcosis. Low-flow oxygen (1-3 L/min) is used. Target SpO2 88-92%.'},
{s:'np3',t:'Respiratory',q:'A client has a chest tube to water seal drainage. The nurse notes continuous bubbling in the water seal chamber. This indicates:',c:['Normal functioning of the system','The lung has fully re-expanded','An air leak in the system','The suction is working properly'],ci:2,r:'Continuous bubbling in the water seal chamber indicates an air leak somewhere in the system — from the chest, tubing connections, or drainage unit. Intermittent bubbling with respirations is normal. Tidaling (fluctuation) indicates proper placement and functioning.'},
{s:'np3',t:'Respiratory',q:'A client with pneumonia is ordered to have postural drainage. When is the BEST time to perform this procedure?',c:['Immediately after meals','30 minutes before meals','2 hours after meals or before meals','Only at bedtime'],ci:1,r:'Postural drainage should be performed 30 minutes before meals or 1-2 hours after meals to prevent nausea and aspiration. It uses gravity to drain secretions from specific lung segments. Percussion, vibration, and deep breathing/coughing follow positioning.'},
{s:'np3',t:'Respiratory',q:'A client is admitted with status asthmaticus. Which medication is the PRIORITY?',c:['Oral corticosteroids','Inhaled long-acting beta-agonist','IV aminophylline','Nebulized short-acting beta-agonist (albuterol)'],ci:3,r:'Short-acting beta-agonists (albuterol/salbutamol) are the first-line bronchodilators for acute asthma attacks. They provide rapid bronchodilation within minutes. IV corticosteroids are added for inflammation. Status asthmaticus is a medical emergency.'},
{s:'np3',t:'Tuberculosis',q:'A client with active TB is admitted. The nurse implements which type of isolation?',c:['Contact precautions','Droplet precautions','Airborne precautions','Standard precautions only'],ci:2,r:'TB requires airborne precautions — negative pressure room, N95 respirator for healthcare workers, and surgical mask on the patient during transport. TB bacilli are transmitted via airborne droplet nuclei that remain suspended in air for hours.'},
{s:'np3',t:'Tuberculosis',q:'Which side effect of isoniazid (INH) requires the nurse to monitor vitamin B6 (pyridoxine) levels?',c:['Hepatotoxicity','Peripheral neuropathy','Optic neuritis','Hyperuricemia'],ci:1,r:'Isoniazid causes peripheral neuropathy by interfering with pyridoxine (vitamin B6) metabolism. Pyridoxine supplementation (25-50mg/day) is routinely given with INH to prevent this side effect, especially in diabetics, alcoholics, and malnourished patients.'},
// GASTROINTESTINAL
{s:'np3',t:'Gastrointestinal',q:'A client with liver cirrhosis develops hepatic encephalopathy. Which dietary modification is MOST important?',c:['Increase protein intake for healing','Restrict protein to reduce ammonia production','Increase sodium intake','Restrict carbohydrates'],ci:1,r:'In hepatic encephalopathy, protein restriction (initially 0.5-1.0 g/kg/day) reduces ammonia production from protein metabolism. Lactulose is given to promote ammonia excretion via stool. As encephalopathy improves, protein is gradually increased.'},
{s:'np3',t:'Gastrointestinal',q:'A client post-gastrectomy develops dumping syndrome 30 minutes after eating. The nurse advises:',c:['Eat three large meals per day','Drink fluids with meals','Eat small frequent meals and lie down after eating','Increase carbohydrate intake'],ci:2,r:'Dumping syndrome management: eat small frequent meals (6 per day), avoid liquids with meals (drink 30-60 min before or after), lie down after eating to slow gastric emptying, avoid simple sugars, and increase protein and fat intake.'},
{s:'np3',t:'Gastrointestinal',q:'Which assessment finding in a client with appendicitis requires IMMEDIATE notification of the physician?',c:['Pain at McBurney\'s point','Rebound tenderness','Sudden relief of abdominal pain followed by diffuse pain','Low-grade fever'],ci:2,r:'Sudden relief of pain followed by diffuse abdominal pain indicates perforation of the appendix. Perforation spreads bacteria throughout the peritoneal cavity causing peritonitis — a life-threatening emergency requiring immediate surgical intervention.'},
{s:'np3',t:'Gastrointestinal',q:'A client with ulcerative colitis is prescribed sulfasalazine. The nurse should instruct the client to:',c:['Take on an empty stomach for best absorption','Drink plenty of water and report orange-colored urine','Avoid all dairy products while taking this drug','Stop if diarrhea develops'],ci:1,r:'Sulfasalazine causes orange-yellow discoloration of urine and skin — a harmless but alarming side effect patients should be warned about. Adequate hydration prevents crystalluria. Folic acid supplementation is needed as the drug interferes with folate absorption.'},
{s:'np3',t:'Gastrointestinal',q:'A client has a new colostomy. Which stool consistency indicates the colostomy is in the sigmoid colon?',c:['Liquid stool','Pasty semi-formed stool','Soft but formed stool','Hard formed stool'],ci:2,r:'The location of the colostomy determines stool consistency. Sigmoid colostomy (most distal) produces soft, formed stool. Descending colostomy produces semi-formed stool. Transverse colostomy produces pasty stool. Ascending/cecostomy produces liquid stool.'},
// MUSCULOSKELETAL
{s:'np3',t:'Musculoskeletal',q:'A client in a long leg cast complains of burning pain, numbness, and tingling in the toes. The nurse should FIRST:',c:['Elevate the extremity higher','Administer prescribed pain medication','Assess the neurovascular status and notify the physician','Apply ice to the cast'],ci:2,r:'Burning pain, numbness, and tingling indicate possible compartment syndrome or nerve compression — a neurovascular emergency. Assess the 6 P\'s (pain, pressure, paralysis, paresthesia, pallor, pulselessness) and notify the physician immediately. Do not elevate if compartment syndrome is suspected.'},
{s:'np3',t:'Musculoskeletal',q:'A client with a fractured hip is placed in Buck\'s traction preoperatively. The purpose of this traction is to:',c:['Permanently correct the fracture alignment','Relieve muscle spasms and reduce pain before surgery','Strengthen leg muscles before surgery','Prevent blood clot formation'],ci:1,r:'Buck\'s traction is skin traction that provides a straight pull on the affected extremity. It relieves painful muscle spasms, maintains alignment, and reduces pain before surgical repair of hip fractures. It is a temporary measure, not definitive treatment.'},
{s:'np3',t:'Orthopedic',q:'A client has a plaster cast applied to the arm. Which finding requires IMMEDIATE intervention?',c:['Mild swelling above and below the cast','Slight warmth over the cast for the first 24 hours','Fingers are pale, cold, and the client cannot move them','Mild itching under the cast'],ci:2,r:'Pale, cold fingers with inability to move them indicate neurovascular compromise — possible compartment syndrome. This requires immediate intervention: notify physician, prepare for cast removal. Early intervention prevents permanent nerve and muscle damage.'},
// NEUROLOGICAL
{s:'np3',t:'Neurological',q:'A client has increased intracranial pressure (ICP). Which position is MOST appropriate?',c:['Trendelenburg position','Head elevated 30 degrees, head midline','Prone position','Flat supine with neck flexed'],ci:1,r:'Head elevation 30 degrees with head in neutral midline position promotes cerebral venous drainage, reducing ICP. Trendelenburg, neck flexion, and activities that increase intrathoracic or abdominal pressure (Valsalva) increase ICP and should be avoided.'},
{s:'np3',t:'Stroke',q:'A client with a left hemisphere stroke would MOST likely have:',c:['Left-sided hemiplegia and left visual field defect','Right-sided hemiplegia and expressive aphasia','Right-sided hemiplegia and impulsive behavior','Left-sided hemiplegia and visual-spatial deficits'],ci:1,r:'The left hemisphere controls speech and language (Broca\'s and Wernicke\'s areas) and movement of the right side of the body. Left hemisphere stroke causes right-sided hemiplegia and aphasia (expressive, receptive, or global). Right hemisphere stroke causes left-sided deficits and visual-spatial problems.'},
{s:'np3',t:'Neurological',q:'A client with Guillain-Barré syndrome is most at risk for which life-threatening complication?',c:['Hypertensive crisis','Respiratory failure from ascending paralysis','Cardiac tamponade','Pulmonary embolism'],ci:1,r:'Guillain-Barré syndrome causes ascending paralysis. When paralysis reaches the respiratory muscles (diaphragm and intercostals), respiratory failure occurs — the most life-threatening complication. Serial respiratory function tests (vital capacity, negative inspiratory force) are monitored closely.'},
// ENDOCRINE
{s:'np3',t:'Diabetes Mellitus',q:'A client with type 1 diabetes develops cold, clammy skin, confusion, and a blood glucose of 45 mg/dL. The PRIORITY intervention is:',c:['Administer insulin as scheduled','Give 15g of fast-acting carbohydrates (Rule of 15)','Call the physician immediately','Administer glucagon IM'],ci:1,r:'The priority for hypoglycemia in a conscious client is the Rule of 15: give 15g fast-acting carbohydrates (4 oz juice, 3-4 glucose tablets), recheck in 15 minutes, and repeat if glucose is still below 70 mg/dL. Glucagon is for unconscious patients who cannot swallow.'},
{s:'np3',t:'Diabetes Mellitus',q:'A client with diabetic ketoacidosis (DKA) has ABG results: pH 7.28, PaCO2 28, HCO3 14. The nurse interprets this as:',c:['Respiratory acidosis','Metabolic alkalosis','Metabolic acidosis with respiratory compensation','Respiratory alkalosis'],ci:2,r:'pH 7.28 (acidosis) + low HCO3 14 (metabolic) + low PaCO2 28 (respiratory compensation via Kussmaul breathing) = metabolic acidosis with respiratory compensation. In DKA, ketone acids lower pH; lungs compensate by blowing off CO2 (Kussmaul respirations).'},
{s:'np3',t:'Endocrine',q:'A client post-thyroidectomy develops tetany. The nurse should prepare to administer:',c:['Potassium chloride IV','Calcium gluconate IV','Magnesium sulfate IV','Sodium bicarbonate IV'],ci:1,r:'Tetany post-thyroidectomy indicates hypocalcemia from inadvertent parathyroid damage or removal. Calcium gluconate 10% IV is given slowly for acute hypocalcemia. Keep calcium gluconate at the bedside for all thyroidectomy clients.'},
// RENAL
{s:'np3',t:'Renal Failure',q:'A client in acute renal failure has a serum potassium of 6.8 mEq/L. The PRIORITY intervention is:',c:['Encourage foods high in potassium','Administer sodium polystyrene sulfonate (Kayexalate)','Prepare for emergency dialysis','Place on cardiac monitor and notify physician immediately'],ci:3,r:'Hyperkalemia of 6.8 mEq/L is life-threatening. The immediate priority is cardiac monitoring (risk of fatal dysrhythmias) and notifying the physician. Treatment may include IV calcium gluconate (cardiac protection), insulin/glucose (shifts K+ into cells), and Kayexalate or dialysis.'},
{s:'np3',t:'Renal Failure',q:'A client with chronic kidney disease (CKD) is on a renal diet. Which food should be AVOIDED?',c:['Apples and blueberries','White bread and pasta','Bananas and potatoes','Egg whites and unsalted crackers'],ci:2,r:'CKD diet restricts potassium (bananas, potatoes, oranges are high in K+), phosphorus (dairy, nuts, cola drinks), sodium, and protein. Apples, blueberries, white bread, egg whites, and unsalted crackers are low-potassium foods appropriate for CKD diet.'},
// ONCOLOGY
{s:'np3',t:'Cancer',q:'A client receiving chemotherapy develops neutropenia with ANC of 400 cells/mm³. The nurse implements:',c:['Contact precautions','Protective (reverse/neutropenic) isolation','Airborne precautions','Standard precautions only'],ci:1,r:'Neutropenic precautions (protective isolation) protect the immunocompromised client from infection. Measures include: private room, strict hand hygiene, no fresh flowers/fruits/vegetables, limit visitors, monitor temperature, and avoid invasive procedures when possible. Normal ANC is 1,500-8,000.'},
{s:'np3',t:'Cancer',q:'A client is receiving doxorubicin (Adriamycin) chemotherapy. The nurse monitors for which life-threatening complication?',c:['Nephrotoxicity','Cardiotoxicity (cardiomyopathy)','Pulmonary fibrosis','Hepatotoxicity'],ci:1,r:'Doxorubicin (anthracycline) causes dose-dependent cardiotoxicity — cardiomyopathy and heart failure. The cumulative lifetime dose is limited. Baseline and periodic cardiac function tests (MUGA scan, echocardiogram) are essential. Extravasation also causes severe tissue necrosis.'},
// BURNS
{s:'np3',t:'Burns',q:'Using the Rule of Nines, a client with burns covering the entire right arm and anterior trunk has what percentage of body surface area burned?',c:['18%','27%','36%','45%'],ci:1,r:'Rule of Nines: each arm = 9%, anterior trunk = 18%. Total = 9% + 18% = 27%. Rule of Nines: head=9%, each arm=9%, anterior trunk=18%, posterior trunk=18%, each leg=18%, perineum=1%. Total=100%.'},
{s:'np3',t:'Burns',q:'During the first 24-48 hours after a major burn, the nurse expects which fluid shift?',c:['Fluid shifts from interstitial to intravascular space','Massive fluid shift from intravascular to interstitial space causing edema','Fluid stays within the vascular space','Lymphatic fluid increases into the blood stream'],ci:1,r:'In the emergent phase (first 24-48 hours), massive capillary leak causes fluid shift from intravascular to interstitial space, causing edema and hypovolemia. This is why aggressive IV fluid resuscitation (Parkland formula) is essential to prevent burn shock.'},
// FLUID AND ELECTROLYTES
{s:'np3',t:'Fluid & Electrolytes',q:'A client has the following ABG results: pH 7.50, PaCO2 50, HCO3 36. The nurse interprets this as:',c:['Respiratory alkalosis','Metabolic acidosis','Metabolic alkalosis with respiratory compensation','Respiratory acidosis with metabolic compensation'],ci:2,r:'pH 7.50 (alkalosis) + high HCO3 36 (metabolic) + high PaCO2 50 (respiratory compensation by retaining CO2) = metabolic alkalosis with respiratory compensation. Common causes include vomiting, NG suctioning, and excessive antacid use.'},
{s:'np3',t:'Fluid & Electrolytes',q:'A client is receiving a hypertonic IV solution. The nurse should monitor for:',c:['Dehydration and decreased blood pressure','Fluid overload and pulmonary edema','Hyperkalemia and cardiac arrhythmias','Metabolic acidosis'],ci:1,r:'Hypertonic solutions (D10W, 3% NaCl) draw water from cells into the vascular space, increasing intravascular volume. This can cause fluid overload and pulmonary edema. Monitor for crackles, dyspnea, and edema. Hypertonic solutions must be administered slowly.'},
// IV THERAPY
{s:'np3',t:'IV Therapy',q:'A client\'s IV site shows redness, warmth, and swelling along the vein track extending 3 inches. The nurse should:',c:['Apply warm compress and continue infusion','Discontinue the IV, apply warm compress, and restart at a new site','Slow the IV rate and monitor','Apply cold compress and report to physician'],ci:1,r:'These findings indicate phlebitis (grade 3 — extensive redness, vein cord palpable). The IV should be discontinued immediately, warm compress applied, and a new IV started at a different site. Document the finding and monitor for infection development.'},
{s:'np3',t:'IV Therapy',q:'The nurse is preparing to administer a blood transfusion. Which of the following is INCORRECT?',c:['Verify blood with two nurses using two patient identifiers','Use normal saline as the priming solution','Start the transfusion slowly for the first 15 minutes','Use dextrose 5% in water as the priming solution'],ci:3,r:'Dextrose solutions cause hemolysis of red blood cells and must NEVER be used with blood transfusions. Only normal saline (0.9% NaCl) is compatible for priming blood transfusion tubing. Stay with the patient for the first 15 minutes — most transfusion reactions occur in this period.'},
// WOUND CARE
{s:'np3',t:'Wound Care',q:'A wound is healing by secondary intention. The nurse understands this means:',c:['The wound edges are sutured together','The wound heals with minimal scarring','The wound is left open and heals through granulation, contraction, and epithelialization','A skin graft is required'],ci:2,r:'Secondary intention healing is used for infected or contaminated wounds too large or infected to close primarily. The wound heals from the inside out through granulation tissue formation, wound contraction, and epithelialization. It results in more scarring and takes longer.'},
{s:'np3',t:'Wound Care',q:'A stage 2 pressure ulcer is characterized by:',c:['Intact skin with non-blanchable redness','Partial thickness skin loss involving epidermis and/or dermis','Full thickness skin loss exposing subcutaneous tissue','Full thickness tissue loss with exposed bone, tendon, or muscle'],ci:1,r:'Stage 2 pressure ulcer: partial thickness loss of dermis presenting as a shallow open ulcer with pink/red wound bed or intact/ruptured blister. Stage 1 = non-blanchable redness. Stage 3 = full thickness. Stage 4 = exposed bone/tendon/muscle.'},
// PERIOPERATIVE
{s:'np3',t:'Perioperative',q:'A client signs a surgical consent form but later tells the nurse she has changed her mind. The nurse should:',c:['Explain the form has been signed and it cannot be changed','Notify the surgeon immediately','Proceed with preoperative preparations as planned','Tell the client she is obligated to have the surgery'],ci:1,r:'Informed consent can be withdrawn at any time before the procedure. The nurse must notify the surgeon immediately when a client withdraws consent. Surgery cannot proceed without valid informed consent. Proceeding without consent constitutes battery.'},
{s:'np3',t:'Perioperative',q:'In the PACU (Post-Anesthesia Care Unit), the nurse assesses an Aldrete score. A score of 8-10 indicates:',c:['The client requires immediate intubation','The client is ready for discharge to the nursing unit','The client requires ICU level of care','The client is in respiratory distress'],ci:1,r:'The Aldrete score assesses activity, respiration, circulation, consciousness, and oxygen saturation (each 0-2 points, max 10). A score of 8-10 indicates the client is stable and ready for discharge from PACU to the nursing unit or home.'},
// PAIN MANAGEMENT
{s:'np3',t:'Pain Management',q:'A client rates pain as 8/10 and states "it feels like my chest is being crushed." The nurse should FIRST:',c:['Administer the prescribed oral analgesic','Document the pain rating in the chart','Assess the character, location, and radiation of the pain','Tell the patient to use relaxation techniques'],ci:2,r:'Further pain assessment is the priority before intervention. Chest pain rated 8/10 with crushing character may indicate MI. Full assessment (PQRST: Provocation, Quality, Radiation, Severity, Timing) determines appropriate intervention — this is not the time for routine analgesics.'},
// NUTRITION
{s:'np3',t:'Nutrition',q:'A client is prescribed a clear liquid diet post-operatively. Which of the following is appropriate?',c:['Milk and pudding','Gelatin, broth, and apple juice','Mashed potatoes and gravy','Yogurt and ice cream'],ci:1,r:'Clear liquid diet includes only transparent liquids: water, clear broth, gelatin, apple juice, popsicles, and clear carbonated beverages. It requires minimal digestion and is used post-op or before procedures. Milk, pudding, yogurt are full liquids.'},
// SAFETY
{s:'np3',t:'Safety',q:'A client is confused and at high risk for falls. Which intervention is the PRIORITY?',c:['Apply wrist restraints','Put the call bell within reach and lower the bed to lowest position','Use a vest restraint to keep client in bed','Keep bed rails up on all four sides'],ci:1,r:'The priority fall prevention intervention is keeping the bed at lowest position with call bell within reach — this is the LEAST restrictive effective measure. Restraints are a last resort, require physician orders, and have serious risks including aspiration, strangulation, and deconditioning.'},
{s:'np3',t:'Safety',q:'When administering medications, the nurse should verify the "rights" of medication administration. Which of the following is NOT one of the traditional 5 rights?',c:['Right patient','Right dose','Right nurse','Right route'],ci:2,r:'The traditional 5 rights of medication administration are: Right Patient, Right Drug, Right Dose, Right Route, and Right Time. "Right nurse" is not one of them. Modern practice also includes Right Documentation, Right Reason, and Right Response.'},
// DELEGATION
{s:'np3',t:'Delegation',q:'Which task is APPROPRIATE for an RN to delegate to an unlicensed assistive personnel (UAP)?',c:['Assess a client\'s pain level after surgery','Administer oral medications','Measure and record vital signs on a stable client','Evaluate a client\'s response to pain medication'],ci:2,r:'Measuring and recording vital signs on a stable client is appropriate for UAP delegation — it is a technical task requiring no nursing judgment. Assessment, administration of medications, and evaluation of responses require nursing judgment and cannot be delegated to UAP.'},
// THERAPEUTIC COMMUNICATION
{s:'np3',t:'Therapeutic Communication',q:'A client says "I\'m afraid I\'m going to die from this surgery." The BEST therapeutic response is:',c:['"Don\'t worry, the surgeon is very experienced."','"Tell me more about what you\'re afraid of."','"Everyone feels that way before surgery."','Silence — leave the room to give privacy'],ci:1,r:'"Tell me more" is an open-ended therapeutic statement that encourages the client to elaborate on feelings without minimizing or dismissing them. False reassurance ("don\'t worry"), generalization ("everyone feels that way"), and avoidance are non-therapeutic responses.'},
// NURSING PROCESS
{s:'np3',t:'Nursing Process',q:'A nurse writes: "Client unable to perform ADLs due to right-sided weakness from CVA." This is an example of which component of the nursing process?',c:['Assessment','Nursing diagnosis','Planning','Implementation'],ci:1,r:'A nursing diagnosis is a clinical judgment about a human response to an actual or potential health condition. It follows the PES format: Problem (unable to perform ADLs), Etiology (right-sided weakness), Signs/Symptoms (from CVA). Assessment collects data; diagnosis interprets it.'},
];
async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} NP3 questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
