const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const questions = [
// MEDSURG
{s:'medsurg',t:'Cardiac',q:'A patient with hypertension is prescribed amlodipine. Which side effect should the nurse monitor?',c:['Bradycardia','Peripheral edema and flushing','Hyperkalemia','Dry cough'],ci:1,r:'Amlodipine is a calcium channel blocker causing vasodilation — peripheral edema and facial flushing are common side effects. Dry cough is associated with ACE inhibitors.'},
{s:'medsurg',t:'Cardiac',q:'A nurse is caring for a patient post-MI on day 2. Which activity is MOST appropriate?',c:['Complete bed rest for 5 days','Passive ROM exercises in bed','Dangling at bedside and gradual ambulation','Full ambulation in the hallway'],ci:1,r:'Early mobilization post-MI follows a graded activity protocol. Day 2 typically involves dangling at the bedside and short-distance ambulation to prevent deconditioning and DVT.'},
{s:'medsurg',t:'Respiratory',q:'A patient with a chest tube develops sudden respiratory distress, tracheal deviation to the right, and absent breath sounds on the left. The nurse suspects:',c:['Hemothorax','Tension pneumothorax','Pleural effusion','Atelectasis'],ci:1,r:'Tension pneumothorax: tracheal deviation AWAY from the affected side, absent breath sounds, and respiratory distress — a life-threatening emergency requiring immediate needle decompression.'},
{s:'medsurg',t:'Respiratory',q:'A nurse is caring for a patient with a water-seal chest tube drainage system. Which finding requires IMMEDIATE intervention?',c:['Gentle bubbling in the water-seal chamber','Fluctuation (tidaling) with respirations','Vigorous continuous bubbling in the water-seal chamber','Drainage of 50mL serosanguineous fluid in 8 hours'],ci:2,r:'Continuous vigorous bubbling in the water-seal chamber indicates an air leak in the system — check all connections. Gentle bubbling may be normal; tidaling is expected.'},
{s:'medsurg',t:'Endocrine',q:'A patient with hypothyroidism is prescribed levothyroxine. Which instruction is MOST important?',c:['Take with food for better absorption','Take at the same time every morning on an empty stomach','Take at bedtime to avoid side effects','Double the dose if one is missed'],ci:1,r:'Levothyroxine is best absorbed on an empty stomach, 30-60 minutes before breakfast. Consistent timing maintains stable thyroid hormone levels.'},
{s:'medsurg',t:'Endocrine',q:'A patient with Addison\'s disease is under emotional stress. The nurse anticipates the need to:',c:['Decrease corticosteroid dose — stress reduces cortisol need','Increase corticosteroid dose — physiologic stress increases cortisol requirements','Discontinue corticosteroids temporarily','Switch to a mineralocorticoid only'],ci:1,r:'Patients with Addison\'s disease cannot produce additional cortisol during stress. Steroid dose must be doubled or tripled during illness, surgery, or significant stress to prevent adrenal crisis.'},
{s:'medsurg',t:'Renal',q:'A patient is scheduled for an IVP (intravenous pyelogram) with contrast dye. Which pre-procedure assessment is MOST important?',c:['NPO status for 4 hours','Allergy to shellfish or iodine','Bowel preparation','Blood glucose level'],ci:1,r:'Contrast dye allergy (iodine/shellfish) is a critical pre-procedure assessment — severe anaphylactic reactions can occur. Renal function (creatinine) must also be checked before contrast use.'},
{s:'medsurg',t:'Gastrointestinal',q:'A patient post-colostomy surgery is concerned about the stoma. Which assessment finding indicates a HEALTHY stoma?',c:['Dark purple, shiny stoma','Pink to red, moist stoma','Pale, dry stoma','Retracted stoma with bleeding'],ci:1,r:'A healthy stoma is pink to red (indicating good perfusion) and moist. Dark purple indicates ischemia; pale suggests poor circulation; retraction and bleeding require immediate assessment.'},
{s:'medsurg',t:'Gastrointestinal',q:'A patient with cirrhosis has massive hematemesis. The PRIORITY nursing action is:',c:['Prepare for endoscopy','Maintain airway and establish IV access','Administer vasopressin as ordered','Insert a Sengstaken-Blakemore tube'],ci:1,r:'Airway is always the first priority — massive hematemesis can cause aspiration and airway obstruction. IV access for fluid resuscitation follows. All other interventions come after stabilization.'},
{s:'medsurg',t:'Neurological',q:'A patient with Parkinson\'s disease is at risk for falls. Which nursing intervention is MOST appropriate?',c:['Encourage fast walking to build confidence','Teach the patient to take small, shuffling steps','Instruct patient to swing arms and take deliberate heel-to-toe steps','Confine the patient to a wheelchair for safety'],ci:2,r:'Parkinson\'s gait (shuffling, festinating) increases fall risk. Teaching deliberate heel-to-toe steps with arm swinging helps overcome the shuffling gait and improves balance.'},
{s:'medsurg',t:'Neurological',q:'A nurse is assessing cranial nerve VII (facial nerve). Which assessment is CORRECT?',c:['Ask the patient to read a chart','Test light touch on the face','Ask the patient to smile, frown, and raise eyebrows','Check the gag reflex'],ci:2,r:'CN VII (facial nerve) controls facial expression. Assessment includes smiling, frowning, raising eyebrows, and puffing cheeks. CN II=vision; CN V=facial sensation; CN IX/X=gag reflex.'},
{s:'medsurg',t:'Musculoskeletal',q:'A patient with rheumatoid arthritis reports morning stiffness lasting 2 hours. The nurse should advise:',c:['Avoid all physical activity to rest the joints','Perform gentle ROM exercises after a warm shower in the morning','Apply ice packs to affected joints before activity','Take NSAIDs only when pain is severe'],ci:1,r:'Morning stiffness in RA improves with warmth and gentle movement. A warm shower followed by gentle ROM exercises helps lubricate joints and reduce stiffness.'},
{s:'medsurg',t:'Immune',q:'A patient with systemic lupus erythematosus (SLE) is being educated. Which statement indicates understanding?',c:['I can sunbathe to improve my vitamin D levels','I should avoid sun exposure and use SPF 50 sunscreen','My symptoms will resolve completely with treatment','I only need to take medications when I have flares'],ci:1,r:'UV exposure triggers SLE flares. Sun protection (SPF 50+, protective clothing, avoiding peak sun hours) is essential. SLE is a chronic condition requiring consistent management.'},
{s:'medsurg',t:'Hematology',q:'A patient with sickle cell crisis is admitted. Which nursing intervention is the PRIORITY?',c:['Administer hydroxyurea','Provide adequate hydration and pain management','Prepare for blood transfusion','Administer supplemental oxygen only'],ci:1,r:'Hydration prevents sickling by reducing blood viscosity. Pain management (opioids for severe crisis) addresses the primary complaint. Both are immediate priorities in sickle cell crisis.'},
{s:'medsurg',t:'Integumentary',q:'A patient with severe burns covering the anterior trunk and both entire arms. Using the Rule of Nines, the TBSA burned is:',c:['27%','36%','45%','54%'],ci:1,r:'Rule of Nines: anterior trunk=18%, each entire arm=9% (x2=18%). Total = 18+18 = 36% TBSA.'},
{s:'medsurg',t:'Eye & Ear',q:'A patient is post-operative for cataract surgery. Which instruction is MOST important?',c:['Sleep on the operative side','Bend at the waist for exercises','Avoid straining, bending, and heavy lifting','Apply warm compress to the eye daily'],ci:2,r:'After cataract surgery, increased intraocular pressure must be avoided. Straining, bending at the waist, and heavy lifting all increase IOP and risk wound disruption.'},
// COMMUNITY (more)
{s:'community',t:'Disaster Nursing',q:'During a mass casualty incident, a patient is breathing 30 times/minute, has a palpable radial pulse, and is unable to follow commands. Using START triage, this patient is tagged:',c:['Green (minor)','Yellow (delayed)','Red (immediate)','Black (expectant)'],ci:2,r:'START triage: breathing present after repositioning OR >30/min = Red. RR >30, pulse present but cannot follow commands = RED (immediate) — critical but salvageable.'},
{s:'community',t:'Disaster Nursing',q:'A nurse is triaging victims of a building collapse. A patient is not breathing even after airway repositioning. Using START triage, this patient is tagged:',c:['Red (immediate)','Yellow (delayed)','Green (minor)','Black (expectant/deceased)'],ci:3,r:'In START triage, no breathing after airway repositioning = BLACK (expectant/deceased). Resources are focused on salvageable patients during mass casualty events.'},
{s:'community',t:'Health Programs',q:'The Philippine government program providing free basic health services to indigent families through PhilHealth is called:',c:['Malasakit Program','Kalusugang Pangkalahatan (Universal Health Care)','4Ps (Pantawid Pamilyang Pilipino Program)','NHTS-PR'],ci:1,r:'Kalusugang Pangkalahatan (Universal Health Care / RA 11223) ensures all Filipinos are automatically enrolled in PhilHealth with access to comprehensive health services.'},
{s:'community',t:'Health Programs',q:'The DOH program that provides free medicines to indigent patients in public hospitals and health centers through a one-stop-shop is:',c:['PhilHealth','Malasakit Center','4Ps Program','DSWD Assistance'],ci:1,r:'The Malasakit Center (RA 11463) provides a one-stop-shop for indigent patients to access free medicines, medical supplies, and financial assistance from DOH, DSWD, PCSO, and PhilHealth.'},
// MATERNAL (more)
{s:'maternal',t:'Gynecology',q:'A patient undergoes a Papanicolaou (Pap) smear. The nurse instructs the patient to:',c:['Douche the night before for cleanliness','Avoid sexual intercourse, douching, and vaginal medications for 48 hours before the test','Schedule during menstruation for best results','Take antibiotics before the procedure'],ci:1,r:'Pap smear accuracy requires avoiding anything that alters cervical cells — intercourse, douching, and vaginal products for 48 hours prior. Menstruation is a contraindication as blood interferes with results.'},
{s:'maternal',t:'Gynecology',q:'A 52-year-old woman reports hot flashes, night sweats, and irregular periods. The nurse recognizes these as symptoms of:',c:['Hypothyroidism','Perimenopause/menopause','Polycystic ovary syndrome','Pelvic inflammatory disease'],ci:1,r:'Hot flashes, night sweats, and menstrual irregularity are classic perimenopausal symptoms caused by declining estrogen levels. Average age of menopause is 51 years.'},
{s:'maternal',t:'Family Planning',q:'A woman asks about natural family planning. The nurse teaches the Billings (cervical mucus) method. Which description of fertile mucus is CORRECT?',c:['Thick, white, and sticky','Thin, clear, stretchy, and slippery (egg white consistency)','Yellow-tinged and odorous','Absent mucus indicates fertility'],ci:1,r:'Fertile cervical mucus (at ovulation) is clear, thin, stretchy (spinnbarkeit), and slippery — resembling raw egg whites. This indicates peak fertility. After ovulation, mucus becomes thick and sticky.'},
{s:'maternal',t:'Pediatric',q:'A 12-month-old child cannot stand alone, says no words, and does not wave bye-bye. The nurse should:',c:['Reassure parents — development varies widely','Document and reassess at 15 months','Refer for developmental evaluation immediately','Recommend more stimulation at home'],ci:2,r:'By 12 months: standing alone, 1-2 words, and gestures (waving) are expected milestones. Absence of all three suggests developmental delay requiring immediate evaluation, not watchful waiting.'},
{s:'maternal',t:'Pediatric',q:'A child is prescribed amoxicillin suspension for otitis media. The parent says "The child\'s ear stopped hurting after 2 days — can we stop the antibiotics?" The nurse should advise:',c:['Yes — if symptoms resolve, antibiotics are no longer needed','Continue the full course even if symptoms resolve to prevent resistance and recurrence','Switch to a stronger antibiotic','Give antibiotics only when symptoms return'],ci:1,r:'Completing the full antibiotic course is essential even after symptom resolution — stopping early leads to incomplete eradication, recurrence, and antibiotic resistance.'},
];

async function seed() {
  const client = await pool.connect();
  let count = 0;
  try {
    for (const q of questions) {
      await client.query(
        `INSERT INTO quiz_items (subject_code, topic_name, question, choices, correct_index, rationale, difficulty)
         VALUES ($1,$2,$3,$4,$5,$6,'medium')`,
        [q.s, q.t, q.q, JSON.stringify(q.c), q.ci, q.r]
      );
      count++;
    }
    console.log(`✅ Inserted ${count} questions!`);
  } finally {
    client.release();
    await pool.end();
  }
}
seed().catch(console.error);
